import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const GIF_DB_URL =
  'https://cdn.jsdelivr.net/gh/JahelCuadrado/ExerciseGymGifsDB@v1.1.0/api/en/exercises.json';

interface GifExercise {
  id: string;
  slug: string;
  name: string;
  muscle: string;
  bodyPart: string;
  equipment: string;
  category: string;
  secondaryMuscles: string[];
  instructions: string[];
  file: string;
  gifUrl: string;
}

const MUSCLE_RU: Record<string, string> = {
  abductors: 'Отводящие',
  abs: 'Пресс',
  abdominals: 'Пресс',
  adductors: 'Приводящие',
  biceps: 'Бицепс',
  calves: 'Икры',
  chest: 'Грудь',
  pectorals: 'Грудь',
  forearms: 'Предплечья',
  glutes: 'Ягодицы',
  hamstrings: 'Задняя поверхность бедра',
  lats: 'Широчайшие',
  'lower back': 'Нижняя спина',
  lower_back: 'Нижняя спина',
  'middle back': 'Средняя спина',
  middle_back: 'Средняя спина',
  neck: 'Шея',
  quadriceps: 'Квадрицепс',
  quads: 'Квадрицепс',
  shoulders: 'Плечи',
  traps: 'Трапеции',
  triceps: 'Трицепс',
  delts: 'Дельты',
  'upper-back': 'Верхняя спина',
  'serratus-anterior': 'Зубчатая мышца',
  'levator-scapulae': 'Мышца шеи',
  cardio: 'Кардио',
  legs: 'Ноги',
};

const WORD_TR: [RegExp, string][] = [
  // Equipment (compound first)
  [/Resistance Band/gi, 'Эспандер'],
  [/Stability Ball/gi, 'Фитбол'],
  [/Exercise Ball/gi, 'Фитбол'],
  [/Bosu Ball/gi, 'Босу'],
  [/Medicine Ball/gi, 'Медбол'],
  [/Tennis Ball/gi, 'Теннисный мяч'],
  [/Smith Machine/gi, 'Тренажер Смит'],
  [/Ez Barbell/gi, 'EZ-Штанга'],
  [/EZ[- ]Bar(?!bell)/gi, 'EZ-гриф'],
  [/Parallel Bars/gi, 'Брусья'],
  [/Barbell/gi, 'Штанга'],
  [/Dumbbell/gi, 'Гантели'],
  [/Kettlebell/gi, 'Гиря'],
  [/Sledge Hammer/gi, 'Кувалда'],
  [/\bSled\b/gi, 'Сани'],
  [/Cable/gi, 'Блок'],
  [/Smith/gi, 'Смит'],
  [/Lever/gi, 'Рычажный тренажер'],
  [/\bBand\b/gi, 'Эспандер'],
  [/\bWheel\b/gi, 'Ролик'],
  [/\bRoller\b/gi, 'Ролик'],
  [/\bRope\b/gi, 'Канат'],
  [/\bPike\b/gi, 'Уголок'],
  [/\bWall\b/gi, 'Стена'],
  [/\bBall\b/gi, 'Мяч'],
  [/\bSMR\b/gi, 'Миофасциальный релиз'],

  // Named movements (compound, must come before single words)
  [/Hip Thrust/gi, 'Ягодичный мостик'],
  [/Pull[- ]Up/gi, 'Подтягивание'],
  [/Push[- ]Up/gi, 'Отжимание'],
  [/Pulldown/gi, 'Тяга вниз'],
  [/Pullovers?\b/gi, 'Пуловер'],
  [/Sit[- ]Up/gi, 'Подъем туловища'],
  [/Leg Raise/gi, 'Подъем ног'],
  [/Leg Curl/gi, 'Сгибание ног'],
  [/Bench Press/gi, 'Жим лежа'],
  [/Leg Press/gi, 'Жим ногами'],
  [/Leg Extension/gi, 'Разгибание ног'],
  [/Hip Abduction/gi, 'Отведение бедра'],
  [/Hip Adduction/gi, 'Приведение бедра'],
  [/Hip Raise/gi, 'Подъем таза'],
  [/Shoulder Press/gi, 'Жим на плечи'],
  [/Chest Press/gi, 'Жим на грудь'],
  [/Chest Fly(e?)\b/gi, 'Разведение на грудь'],
  [/Bent[- ]Over\b/gi, 'В наклоне'],
  [/Close[- ]Grip/gi, 'Узким хватом'],
  [/Wide[- ]Grip/gi, 'Широким хватом'],
  [/Romanian Deadlift/gi, 'Румынская становая тяга'],
  [/Stiff[- ]Leg(ged)?/gi, 'На прямых ногах'],
  [/Mountain Climber/gi, 'Альпинист'],
  [/Side Bend/gi, 'Наклон в сторону'],
  [/Side Raise/gi, 'Подъем в сторону'],
  [/Front Raise/gi, 'Подъем перед собой'],
  [/Lateral Raise/gi, 'Подъем в стороны'],
  [/Rear Deltoid/gi, 'Задняя дельтовидная'],
  [/Rear Delt/gi, 'Задние дельты'],
  [/Calf Raise/gi, 'Подъем на носки'],
  [/Good Morning/gi, 'Наклон с отягощением'],
  [/Russian Twist/gi, 'Русское скручивание'],
  [/Nordic Curl/gi, 'Скандинавский подъем'],
  [/Dead Bug/gi, 'Мертвый жук'],
  [/Donkey Kick/gi, 'Удар ослика'],
  [/Fire Hydrant/gi, 'Пожарный гидрант'],
  [/Bird Dog/gi, 'Птичья собака'],
  [/Box Jump/gi, 'Запрыгивание на тумбу'],
  [/Step[- ]Up/gi, 'Зашаг на ступеньку'],
  [/Chin[- ]Up/gi, 'Подтягивание обратным хватом'],
  [/Muscle[- ]Up/gi, 'Подъем с переворотом'],
  [/Toes[- ]To[- ]Bar/gi, 'Подъем ног к перекладине'],
  [/Knee[- ]Raise/gi, 'Подъем коленей'],
  [/Face[- ]Pull/gi, 'Тяга к лицу'],
  [/Hip[- ]Hinge/gi, 'Наклон бедром'],
  [/Cross[- ]Body/gi, 'Перекрестный'],
  [/Cross[- ]Bench/gi, 'Поперечная скамья'],
  [/One[- ]?Arm\b/gi, 'Одной рукой'],
  [/Single[- ]Arm/gi, 'Одной рукой'],
  [/Single[- ]Leg/gi, 'На одной ноге'],
  [/Two[- ]?Arm\b/gi, 'Двумя руками'],
  [/Flat Bench/gi, 'Горизонтальная скамья'],
  [/Over the [Hh]ead/gi, 'Над головой'],
  [/Claps? [Oo]ver/gi, 'Хлопки над'],
  [/\bClaps?\b/gi, 'Хлопки'],
  [/\bCommando\b/gi, 'Коммандо'],
  [/Internal Rotation/gi, 'Внутреннее вращение'],
  [/External Rotation/gi, 'Внешнее вращение'],
  [/Battling Ropes?/gi, 'Боевые канаты'],
  [/Bear Crawl/gi, 'Медвежья ходьба'],
  [/Around[- ]The[- ]World/gi, 'Вокруг мира'],
  [/Around World/gi, 'Вокруг мира'],
  [/Iron Cross/gi, 'Железный крест'],
  [/Figure[- ]?8/gi, 'Восьмерка'],
  [/Anti[- ]Gravity/gi, 'Антигравитационный'],
  [/Seesaw/gi, 'Качели'],
  [/Air Bike/gi, 'Воздушный велосипед'],
  [/Star Jump/gi, 'Звёздный прыжок'],
  [/Butt Ups?\b/gi, 'Подъем ягодиц'],
  [/Bottoms? Up\b/gi, 'Подъем дна'],
  [/Pelvic Tilt/gi, 'Наклон таза'],
  [/Jack[- ]?knife/gi, 'Складной нож'],
  [/Throw Down/gi, 'Бросок вниз'],
  [/Rectus Femoris/gi, 'Прямая мышца бедра'],
  [/Yoga Pose/gi, 'Поза йоги'],
  [/Spell Caster/gi, 'Заклинатель'],
  [/Captains? Chair/gi, 'Кресло капитана'],
  [/Bradford Press/gi, 'Жим Брэдфорда'],
  [/Concentration Curl/gi, 'Концентрированный подъем'],
  [/Wind Sprints?/gi, 'Ветряные спринты'],
  [/L[- ]?Sit\b/gi, 'L-сит'],
  [/V[- ]?Sit\b/gi, 'V-сит'],
  [/\bPreacher\b/gi, 'на скамье Скотта'],
  [/\bPeacher\b/gi, 'на скамье Скотта'],
  [/\bConcentration\b/gi, 'Концентрированный'],
  [/\bHammer\b/gi, 'Молоток'],
  [/\bDrag\b/gi, 'Протяжка'],
  [/\bGrip\b/gi, 'Хват'],
  [/\bZottman\b/gi, 'Цоттман'],
  [/\bSpider\b/gi, 'Паук'],
  [/\bDonkey\b/gi, 'Ослик'],
  [/\bMilitary\b/gi, 'Военный'],
  [/\bBradford\b/gi, 'Брэдфорд'],
  [/\bOlympic\b/gi, 'Олимпийская'],
  [/\bCuban\b/gi, 'Кубинский'],
  [/\bTurkish\b/gi, 'Турецкий'],
  [/\bScott\b/gi, 'Скотта'],
  [/\bRocky\b/gi, 'Рокки'],
  [/\bSkier\b/gi, 'Лыжник'],
  [/\bThruster\b/gi, 'Траст'],
  [/Deadlift/gi, 'Становая тяга'],
  [/Butterfly/gi, 'Бабочка'],

  // Single movement words (with -ing suffix fixes)
  [/\bFlye?s?\b/gi, 'Разведение'],
  [/\bTwist(ing)?\b/gi, 'Скручивание'],
  [/\bSquats?(ting)?\b/gi, 'Приседание'],
  [/\bLunges?\b/gi, 'Выпад'],
  [/\bCrunch(es)?\b/gi, 'Скручивание'],
  [/\bPlank\b/gi, 'Планка'],
  [/\bShrugs?\b/gi, 'Шраги'],
  [/\bSwings?\b/gi, 'Мах'],
  [/\bBridge\b/gi, 'Мостик'],
  [/\bDip\b/gi, 'Отжимание на брусьях'],
  [/\bSnatch\b/gi, 'Рывок'],
  [/\bClean\b/gi, 'Подъем на грудь'],
  [/\bJerk\b/gi, 'Толчок'],
  [/Windmill/gi, 'Мельница'],
  [/Burpees?/gi, 'Бёрпи'],
  [/Stretch(ing)?\b/gi, 'Растяжка'],
  [/\bKick\b/gi, 'Удар'],
  [/\bJumps?\b/gi, 'Прыжок'],
  [/\bHop\b/gi, 'Прыжок'],
  [/Rollout/gi, 'Прокатка'],
  [/Rollerout/gi, 'Прокатка'],
  [/\bPress\b/gi, 'Жим'],
  [/\bCurls?\b/gi, 'Подъем'],
  [/\bRows?\b/gi, 'Тяга'],
  [/\bRaises?\b/gi, 'Подъем'],
  [/\bExtension\b/gi, 'Разгибание'],
  [/\bFlexion\b/gi, 'Сгибание'],

  // Position & modifier words
  [/Alternating/gi, 'Поочередный'],
  [/Alternate/gi, 'Поочередный'],
  [/Assisted/gi, 'С помощью'],
  [/Incline/gi, 'На наклонной скамье'],
  [/Decline/gi, 'Наклонный вниз'],
  [/Seated|Sitted/gi, 'Сидя'],
  [/Standing/gi, 'Стоя'],
  [/Lying/gi, 'Лежа'],
  [/Kneeling/gi, 'На коленях'],
  [/Hanging/gi, 'В висе'],
  [/Suspended/gi, 'На подвесе'],
  [/Overhead/gi, 'Над головой'],
  [/Reverse/gi, 'Обратный'],
  [/Underhand/gi, 'Обратным хватом'],
  [/Overhand/gi, 'Прямым хватом'],
  [/Bilateral/gi, 'Двусторонний'],
  [/Unilateral/gi, 'Односторонний'],
  [/\bSingle\b/gi, 'Односторонний'],
  [/\bDouble\b/gi, 'Двусторонний'],
  [/Straight/gi, 'Прямой'],
  [/\bBent\b/gi, 'Согнутый'],
  [/\bFull\b/gi, 'Полный'],
  [/\bHalf\b/gi, 'Частичный'],
  [/\bInner\b/gi, 'Внутренний'],
  [/\bOuter\b/gi, 'Внешний'],
  [/\bUpper\b/gi, 'Верхний'],
  [/\bLower\b/gi, 'Нижний'],
  [/\bFront\b/gi, 'Передний'],
  [/\bRear\b/gi, 'Задний'],
  [/Lateral/gi, 'Боковой'],
  [/Diagonal/gi, 'Диагональный'],
  [/Supine/gi, 'Лежа на спине'],
  [/Prone/gi, 'Лежа на животе'],
  [/Advanced/gi, 'Усложненный'],
  [/Modified/gi, 'Модифицированный'],
  [/\bBasic\b/gi, 'Базовый'],
  [/Weighted/gi, 'С отягощением'],
  [/Bodyweight/gi, 'Вес тела'],
  [/\bNarrow\b/gi, 'Узкий'],
  [/\bDeep\b/gi, 'Глубокий'],
  [/\bFlat\b/gi, 'Горизонтальный'],
  [/Vertical/gi, 'Вертикальный'],
  [/Horizontal/gi, 'Горизонтальный'],
  [/\bNegative\b/gi, 'Негативный'],
  [/\bTuck\b/gi, 'Группировка'],
  [/\bStraddle\b/gi, 'Широкая стойка'],
  [/\bLean\b/gi, 'С наклоном'],
  [/Posterior/gi, 'Задний'],
  [/\bPrisoner\b/gi, 'Заключенный'],
  [/\bQuarter\b/gi, 'Четверть'],
  [/\bPower\b/gi, 'Силовой'],
  [/\bPotty\b/gi, 'Низкий'],

  // Named exercises / animals / objects
  [/\bArnold\b/gi, 'Арнольда'],
  [/\bPallof\b/gi, 'Паллоф'],
  [/Romanian/gi, 'Румынский'],
  [/Bulgarian/gi, 'Болгарский'],
  [/\bSumo\b/gi, 'Сумо'],
  [/\bHack\b/gi, 'Гак'],
  [/\bPendlay\b/gi, 'Пендлей'],
  [/Jefferson/gi, 'Джефферсон'],
  [/\bZercher\b/gi, 'Зерхер'],
  [/Landmine/gi, 'Наклонный гриф'],
  [/\bGoblet\b/gi, 'Кубок'],
  [/Suitcase/gi, 'Чемодан'],
  [/\bNordic\b/gi, 'Скандинавский'],
  [/\bInchworm\b/gi, 'Гусеница'],
  [/\bBicycle\b/gi, 'Велосипед'],
  [/\bFrog\b/gi, 'Лягушка'],
  [/\bPlanche\b/gi, 'Планш'],
  [/\bMaltese\b/gi, 'Мальтийский крест'],
  [/\bGorilla\b/gi, 'Горилла'],
  [/\bFlag\b/gi, 'Флаг'],
  [/\bCrab\b/gi, 'Краб'],
  [/\bCocoons?\b/gi, 'Кокон'],
  [/\bSlingers?\b/gi, 'Маятник'],
  [/\bJanda\b/gi, 'Янда'],
  [/\bJudo\b/gi, 'Дзюдо'],
  [/\bYoga\b/gi, 'Йога'],
  [/\bGorilla\b/gi, 'Горилла'],
  [/\bKorean\b/gi, 'Корейский'],
  [/\bClock\b/gi, 'Часовые'],
  [/\bDynamic\b/gi, 'Динамический'],
  [/\bHeavy\b/gi, 'Тяжелый'],
  [/\bThrust\b/gi, 'Толчок вперед'],
  [/\bExtended\b/gi, 'Расширенный'],
  [/\bHyght\b/gi, 'Высокий'],
  [/\bReverse\b/gi, 'Обратный'],

  // Body parts
  [/Hamstring/gi, 'Задняя поверхность бедра'],
  [/Quadricep/gi, 'Квадрицепс'],
  [/\bGlutes?\b/gi, 'Ягодицы'],
  [/\bDelts?\b/gi, 'Дельты'],
  [/\bShoulder\b/gi, 'Плечо'],
  [/Forearm/gi, 'Предплечье'],
  [/\bBiceps?\b/gi, 'Бицепс'],
  [/\bTriceps?\b/gi, 'Трицепс'],
  [/Oblique/gi, 'Косая мышца'],
  [/Abdominal/gi, 'Пресс'],
  [/Adductor/gi, 'Приводящая'],
  [/Abductor/gi, 'Отводящая'],
  [/\bCalf\b/gi, 'Икры'],
  [/\bHip\b/gi, 'Бедро'],
  [/\bLegs?\b/gi, 'Ноги'],
  [/\bArms?\b/gi, 'Руки'],
  [/\bElbows?\b/gi, 'Локоть'],
  [/\bHands?\b/gi, 'Руки'],
  [/\bKnees?\b/gi, 'Колено'],
  [/\bToe\b/gi, 'Носок'],
  [/\bHeel\b/gi, 'Пятка'],
  [/\bTap\b/gi, 'Касание'],
  [/\bBack\b/gi, 'Спина'],
  [/\bChest\b/gi, 'Грудь'],
  [/\bNeck\b/gi, 'Шея'],
  [/\bAbs?\b/gi, 'Пресс'],
  [/\bCore\b/gi, 'Кор'],
  [/\bSpine\b/gi, 'Позвоночник'],
  [/\bGroin\b/gi, 'Пах'],

  // Body parts (additional)
  [/\bAnkles?\b/gi, 'Лодыжка'],
  [/\bWrists?\b/gi, 'Запястье'],
  [/\bChin\b/gi, 'Подбородок'],
  [/Peroneals?\b/gi, 'Малоберцовые'],
  [/Tibialis\b/gi, 'Большеберцовая'],
  [/\bCalves\b/gi, 'Икры'],
  [/\bDeltoid\b/gi, 'Дельтовидная'],
  [/\bPiriformis\b/gi, 'Грушевидная мышца'],
  [/\bFinger\b/gi, 'Пальцы'],

  // Common single words
  [/\bBench\b/gi, 'Скамья'],
  [/\bBags?\b/gi, 'Мешок'],
  [/\bMachine\b/gi, 'Тренажер'],
  [/\bBar\b/gi, 'Гриф'],
  [/\bFloor\b/gi, 'Пол'],
  [/\bBehind\b/gi, 'За'],
  [/\bAgainst\b/gi, 'у'],
  [/\bBetween\b/gi, 'между'],
  [/\bUnder\b/gi, 'Под'],
  [/\bRange\b/gi, 'Диапазон'],
  [/\bReach\b/gi, 'Потянуться'],
  [/\bStep\b/gi, 'Шаг'],
  [/\bLift\b/gi, 'Подъем'],
  [/\bThrow\b/gi, 'Бросок'],
  [/\bSlam\b/gi, 'Удар об пол'],
  [/\bPush\b/gi, 'Жим'],
  [/\bPull\b/gi, 'Тяга'],
  [/\bFallout\b/gi, 'Выпад вперед'],
  [/\bSaw\b/gi, 'Пила'],
  [/\bFlip\b/gi, 'Переворот'],
  [/Attachment/gi, 'Рукоятка'],
  [/\bMotion\b/gi, 'Движение'],
  [/Blaster/gi, 'Усилитель'],
  [/\bBalance\b/gi, 'Баланс'],
  [/Stabilization/gi, 'Стабилизация'],
  [/\bRotation\b/gi, 'Вращение'],
  [/\bCircular\b/gi, 'Круговой'],
  [/\bStationary\b/gi, 'Стационарный'],
  [/\bTreadmill\b/gi, 'Беговая дорожка'],
  [/\bElliptical\b/gi, 'Эллиптический'],
  [/\bStepmill\b/gi, 'Степмилл'],
  [/\bBike\b/gi, 'Велосипед'],
  [/\bCycle\b/gi, 'Велотренажер'],
  [/\bNeutral\b/gi, 'Нейтральный'],
  [/\bHigh\b/gi, 'Высокий'],
  [/\bLow\b/gi, 'Нижний'],
  [/\bHead\b/gi, 'Голова'],
  [/\bHang(ing)?\b/gi, 'Вис'],
  [/\bSupport\b/gi, 'С опорой'],
  [/\bCarry\b/gi, 'Переноска'],
  [/\bCross\b/gi, 'Крест'],
  [/\bParallel\b/gi, 'Параллельно'],
  [/\bRound\b/gi, 'Круговой'],
  [/\bAbove\b/gi, 'Над'],
  [/\bPalms?\b/gi, 'Ладонь'],
  [/\bStance\b/gi, 'Стойка'],
  [/\bStaircase\b/gi, 'Лестница'],
  [/\bBends?\b/gi, 'Сгибание'],
  [/\bScissor\b/gi, 'Ножницы'],
  [/\bSemi\b/gi, 'Полу'],
  [/\bAstride\b/gi, 'Широкий шаг'],
  [/\bForth\b/gi, 'Вперед'],
  [/\bShort\b/gi, 'Короткий'],
  [/\bSkater\b/gi, 'Конькобежец'],
  [/\bSki\b/gi, 'Лыжный'],
  [/\bMarch\b/gi, 'Марш'],
  [/\bHook\b/gi, 'Хук'],
  [/\bBoxing\b/gi, 'Бокс'],
  [/\bStirrups?\b/gi, 'Стремена'],
  [/\bSupination\b/gi, 'Супинация'],
  [/\bPronation\b/gi, 'Пронация'],
  [/\bHyper\b/gi, 'Гипер'],
  [/\bIron\b/gi, 'Железный'],
  [/\bCan\b/gi, 'Полный'],
  [/\bClassped\b/gi, 'Сцепленные'],
  [/\bClassp(ed)?\b/gi, 'Сцепленные'],
  [/\bClasped?\b/gi, 'Сцепленные'],
  [/\bPirate\b/gi, 'Пиратский'],
  [/\bSuper\b/gi, 'Супер'],
  [/\bSternum\b/gi, 'Грудина'],
  [/\bInternal\b/gi, 'Внутренний'],
  [/\bExternal\b/gi, 'Внешний'],
  [/\bTract\b/gi, 'Тяга'],
  [/\bWorld\b/gi, 'Мир'],
  [/\bStyle\b/gi, 'Стиль'],
  [/\bStride\b/gi, 'Шаг'],
  [/\bPoint\b/gi, 'Точка'],
  [/\bLeft\b/gi, 'Левый'],
  [/\bRight\b/gi, 'Правый'],
  [/Pushdown/gi, 'Жим вниз'],
  [/\bLats?\b/gi, 'Широчайшие'],
  [/\bInverse\b/gi, 'Обратный'],
  [/\bThrough\b/gi, 'Сквозь'],
  [/\bSelf\b/gi, 'Само'],
  [/\bPlyo\w*/gi, 'Плиометрический'],
  [/\bFlexors?\b/gi, 'Сгибатель'],
  [/\bSqueeze\b/gi, 'Сжатие'],
  [/\bRetractors?\b/gi, 'Сводящий'],
  [/\bIsometric\b/gi, 'Изометрический'],
  [/\bFixed\b/gi, 'Фиксированный'],
  [/\bDrop\b/gi, 'Сброс'],
  [/\bPistol\b/gi, 'Пистолет'],
  [/\bPass\b/gi, 'Передача'],
  [/\bKicks?\b/gi, 'Удар'],
  [/\bJack\b/gi, 'Прыжок'],
  [/\bPose\b/gi, 'Поза'],
  [/\bSqueeze\b/gi, 'Сжатие'],
  [/\bHyperextensions?\b/gi, 'Гиперэкстензия'],
  [/\bRotates?\b/gi, 'Вращение'],
  [/\bLifting\b/gi, 'Подъем'],
  [/\bEquipment\b/gi, 'Оборудование'],
  [/\bHops?\b/gi, 'Прыжок'],
  [/\bGluteus\b/gi, 'Ягодичная мышца'],
  [/\bGrippers?\b/gi, 'Захват'],
  [/\bApart\b/gi, 'В стороны'],
  [/\bRack\b/gi, 'Стойка'],
  [/\bSpeed\b/gi, 'Скоростной'],
  [/\bSprint\b/gi, 'Спринт'],
  [/Curtsey|Curtsy/gi, 'Реверанс'],
  [/Contralateral/gi, 'Контрлатеральный'],
  [/\bStepbox\b/gi, 'Ступенька'],
  [/\bLegged\b/gi, 'ногий'],
  [/\bFlutter\b/gi, 'Флаттер'],
  [/Frankenstein/gi, 'Франкенштейн'],
  [/\bGet\b/gi, 'Подъем'],
  [/\bInto\b/gi, 'в'],
  [/\bCobra\b/gi, 'Кобра'],
  [/\bMonster\b/gi, 'Монстр'],
  [/\bOutside\b/gi, 'Снаружи'],
  [/\bInside\b/gi, 'Внутри'],
  [/\bOutstretched\b/gi, 'Вытянутый'],
  [/\bDegrees?\b/gi, 'Градусов'],
  [/\bCloser\b/gi, 'Ближе'],
  [/\bInverted\b/gi, 'Перевернутый'],
  [/\bHandstand\b/gi, 'Стойка на руках'],
  [/\bDips?\b/gi, 'Отжимание на брусьях'],
  [/\bChairs?\b/gi, 'Стул'],
  [/\bSkull\b/gi, 'Французский'],
  [/\bRenegade\b/gi, 'Ренегат'],
  [/\bRelease\b/gi, 'Расслабление'],
  [/\bQuick\b/gi, 'Быстрый'],
  [/\bQuads?\b/gi, 'Квадрицепс'],
  [/\bMixed\b/gi, 'Смешанный'],
  [/\bMiddle\b/gi, 'Средний'],
  [/\bHandles?\b/gi, 'Рукоятка'],
  [/\bFrench\b/gi, 'Французский'],
  [/\bChains?\b/gi, 'Цепь'],
  [/\bCatch\b/gi, 'Поймать'],
  [/\bCars?\b/gi, 'Машина'],
  [/\bBoxes?\b/gi, 'Тумба'],
  [/\bBelow\b/gi, 'Ниже'],
  [/\bBands?\b/gi, 'Эспандер'],
  [/\bAtlas\b/gi, 'Атлас'],
  [/\bArchers?\b/gi, 'Лучник'],
  [/\bSit\b/gi, 'Сед'],
  [/\bPov\b/gi, ''],
  [/\bResponse\b/gi, ''],
  [/\bA\b/g, ''],
  [/\bWaiter\b/gi, 'Официант'],
  [/\bStork\b/gi, 'Аист'],
  [/\bBowling\b/gi, 'Боулинг'],
  [/\bPalm\b/gi, 'Ладонь'],
  [/\bPad\b/gi, 'Накладка'],
  [/\bBody\b/gi, 'Тело'],
  [/\bHug\b/gi, 'Обхват'],
  [/\bKeens?\b/gi, 'Колени'],
  [/Circles?\b/gi, 'Круг'],
  [/Touchers?\b/gi, 'Касание'],
  [/\bTouch\b/gi, 'Касание'],
  [/\bRocking\b/gi, 'Раскачивание'],
  [/\bAngled\b/gi, 'Под углом'],
  [/\bForward\b/gi, 'Вперед'],
  [/\bRevers\b/gi, 'Обратный'],
  [/\bTwisted\b/gi, 'Скрученный'],
  [/\bUpright\b/gi, 'Вертикальный'],
  [/\bTrainers?\b/gi, 'Тренажер'],
  [/\bWalk(ing)?\b/gi, 'Ходьба'],
  [/\bRunning\b/gi, 'Бег'],
  [/\bRun\b/gi, 'Бег'],
  [/\bRotary\b/gi, 'Ротационный'],
  [/\bTennis\b/gi, 'Теннисный'],
  [/\bPosition\b/gi, 'Положение'],
  [/\bSide\b/gi, 'Боковой'],
  [/\bWide\b/gi, 'Широкий'],
  [/\bOne\b/gi, 'Одно'],
  [/\bTwo\b/gi, 'Два'],
  [/\bBoth\b/gi, 'Обе'],
  [/\bWith\b/gi, 'с'],
  [/\bFrom\b/gi, 'из'],
  [/\bOver\b/gi, 'Над'],
  [/\bOn\b/gi, 'на'],
  [/\bAnd\b/gi, 'и'],
  [/\bThe\b/gi, ''],
  [/\bUp\b/gi, 'вверх'],
  [/\bDown\b/gi, 'вниз'],
  [/\bTo\b/gi, 'к'],
  [/\bIn\b/gi, 'в'],
  [/\bv[- ]?(\d+)\b/gi, 'вар.$1'],
  [/\bFemale\b/gi, '(ж)'],
  [/\bMale\b/gi, '(м)'],
];

function translateName(name: string): string {
  let result = name;
  for (const [pattern, replacement] of WORD_TR) {
    result = result.replace(pattern, replacement);
  }
  result = result.replace(/\s{2,}/g, ' ').trim();
  return result.charAt(0).toUpperCase() + result.slice(1);
}

async function main() {
  console.log('Fetching exercises from ExerciseGymGifsDB...');
  const gifRes = await fetch(GIF_DB_URL);
  if (!gifRes.ok) throw new Error(`GifDB fetch failed: ${gifRes.status}`);
  const gifData = (await gifRes.json()) as { count: number; exercises: GifExercise[] };
  console.log(`GifDB: ${gifData.count} exercises`);

  await prisma.exercise.deleteMany();
  console.log('Cleared existing exercises. Seeding GIF exercises only...');

  const gifRecords = gifData.exercises.map((ex) => ({
    id: ex.id,
    name: ex.name,
    nameRu: translateName(ex.name),
    category: MUSCLE_RU[ex.muscle] ?? ex.muscle,
    primaryMuscles: [ex.muscle],
    secondaryMuscles: ex.secondaryMuscles,
    equipment: ex.equipment ?? null,
    images: [ex.gifUrl],
  }));

  const result = await prisma.exercise.createMany({
    data: gifRecords,
    skipDuplicates: true,
  });

  console.log(`Done! Seeded ${result.count} GIF exercises.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
