import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';

const prisma = new PrismaClient();

interface RawExercise {
  id: string;
  name: string;
  category: string;
  primaryMuscles: string[];
  secondaryMuscles: string[];
  equipment: string;
  images: string[];
}

const TRANSLATIONS: Record<string, string> = {
  '3_4_Sit-Up': 'Скручивания на 3/4',
  '90_90_Hamstring': 'Растяжка задней поверхности бедра 90/90',
  'Ab_Crunch_Machine': 'Тренажер для скручиваний на пресс',
  'Ab_Roller': 'Ролик для пресса',
  'Adductor': 'Сведение ног в тренажере',
  'Adductor_Groin': 'Растяжка приводящих мышц и паха',
  'Advanced_Kettlebell_Windmill': 'Усложненная мельница с гирей',
  'Air_Bike': 'Аэробайк',
  'All_Fours_Quad_Stretch': 'Растяжка квадрицепсов на четвереньках',
  'Alternate_Hammer_Curl': 'Поочередный подъем гантелей «Молот»',
  'Alternate_Heel_Touchers': 'Поочередное касание пяток лежа',
  'Alternate_Incline_Dumbbell_Curl': 'Поочередный подъем гантелей на бицепс на наклонной скамье',
  'Alternate_Leg_Diagonal_Bound': 'Диагональные прыжки с ноги на ногу',
  'Alternating_Cable_Shoulder_Press': 'Поочередный жим на плечи на блоке',
  'Alternating_Deltoid_Raise': 'Поочередный подъем рук на дельты',
  'Alternating_Floor_Press': 'Поочередный жим с пола',
  'Alternating_Hang_Clean': 'Поочередное взятие на грудь с виса',
  'Alternating_Kettlebell_Press': 'Поочередный жим гирь',
  'Alternating_Kettlebell_Row': 'Поочередная тяга гири в наклоне',
  'Alternating_Renegade_Row': 'Поочередная тяга «Ренегат»',
  'Ankle_Circles': 'Вращения голеностопом',
  'Ankle_On_The_Knee': 'Растяжка ягодиц сидя (лодыжка на колене)',
  'Anterior_Tibialis-SMR': 'Передняя большеберцовая-СМР',
  'Anti-Gravity_Press': 'Антигравитационный жим',
  'Arm_Circles': 'Круговые вращения руками',
  'Arnold_Dumbbell_Press': 'Жим Арнольда с гантелями',
  'Around_The_Worlds': 'Разведения рук «Вокруг света»',
  'Atlas_Stone_Trainer': 'Тренажер для подъема камней Атласа',
  'Atlas_Stones': 'Подъем камней Атласа',
  'Axle_Deadlift': 'Становая тяга с толстым грифом',
  'Back_Flyes_-_With_Bands': 'Разведения на задние дельты с эспандером',
  'Backward_Drag': 'Ходьба назад с тягой саней',
  'Backward_Medicine_Ball_Throw': 'Бросок медбола назад через голову',
  'Balance_Board': 'Балансировочная доска',
  'Ball_Leg_Curl': 'Сгибание ног на фитболе лежа',
  'Band_Assisted_Pull-Up': 'Подтягивания с резиновой петлей',
  'Band_Good_Morning': 'Наклоны «Доброе утро» с эспандером',
  'Band_Good_Morning_Pull_Through': 'Тяга между ног с эспандером',
  'Band_Hip_Adductions': 'Приведение бедра с эспандером',
  'Band_Pull_Apart': 'Растягивание эспандера перед собой',
  'Band_Skull_Crusher': 'Французский жим с эспандером',
  'Barbell_Ab_Rollout': 'Выкатывание со штангой на пресс',
  'Barbell_Ab_Rollout_-_On_Knees': 'Выкатывание со штангой с колен',
  'Barbell_Bench_Press_-_Medium_Grip': 'Жим штанги лежа средним хватом',
  'Barbell_Curl': 'Подъем штанги на бицепс стоя',
  'Barbell_Curls_Lying_Against_An_Incline': 'Подъем штанги на бицепс лежа на наклонной скамье',
  'Barbell_Deadlift': 'Становая тяга со штангой',
  'Barbell_Full_Squat': 'Глубокий присед со штангой',
  'Barbell_Glute_Bridge': 'Ягодичный мостик со штангой',
  'Barbell_Guillotine_Bench_Press': 'Жим штанги лежа к шее',
  'Barbell_Hack_Squat': 'Гакк-приседания со штангой',
  'Barbell_Hip_Thrust': 'Подъем таза со штангой',
  'Barbell_Incline_Bench_Press_-_Medium_Grip': 'Жим штанги на наклонной скамье средним хватом',
  'Barbell_Incline_Shoulder_Raise': 'Подъем плеч со штангой на наклонной скамье',
  'Barbell_Lunge': 'Выпады со штангой',
  'Barbell_Rear_Delt_Row': 'Тяга штанги на заднюю дельту',
  'Barbell_Rollout_from_Bench': 'Выкатывание со штангой со скамьи',
  'Barbell_Seated_Calf_Raise': 'Подъем на носки сидя со штангой',
  'Barbell_Shoulder_Press': 'Армейский жим штанги',
  'Barbell_Shrug': 'Шраги со штангой',
  'Barbell_Shrug_Behind_The_Back': 'Шраги со штангой за спиной',
  'Barbell_Side_Bend': 'Наклоны в стороны со штангой',
  'Barbell_Side_Split_Squat': 'Боковые сплит-приседания со штангой',
  'Barbell_Squat': 'Приседания со штангой',
  'Barbell_Squat_To_A_Bench': 'Приседания со штангой на скамью',
  'Barbell_Step_Ups': 'Зашагивания на платформу со штангой',
  'Barbell_Walking_Lunge': 'Выпады со штангой при ходьбе',
  'Battling_Ropes': 'Боевые канаты',
  'Bear_Crawl_Sled_Drags': 'Тяга саней медвежьим шагом',
  'Behind_Head_Chest_Stretch': 'Растяжка грудных мышц с руками за головой',
  'Bench_Dips': 'Обратные отжимания от скамьи',
  'Bench_Jump': 'Запрыгивания на скамью',
  'Bench_Press_-_Powerlifting': 'Жим лежа (пауэрлифтинг)',
  'Bench_Press_-_With_Bands': 'Жим лежа с резиновыми петлями',
  'Bench_Press_with_Chains': 'Жим лежа с цепями',
  'Bench_Sprint': 'Спринт на скамье',
  'Bent-Arm_Barbell_Pullover': 'Пуловер со штангой на согнутых руках',
  'Bent-Arm_Dumbbell_Pullover': 'Пуловер с гантелью на согнутых руках',
  'Bent-Knee_Hip_Raise': 'Подъем коленей лежа на спине',
  'Bent_Over_Barbell_Row': 'Тяга штанги в наклоне',
  'Bent_Over_Dumbbell_Rear_Delt_Raise_With_Head_On_Bench': 'Разведения гантелей в наклоне с упором лбом в скамью',
  'Bent_Over_Low-Pulley_Side_Lateral': 'Махи назад с нижнего блока в наклоне',
  'Bent_Over_One-Arm_Long_Bar_Row': 'Тяга конца грифа одной рукой в наклоне',
  'Bent_Over_Two-Arm_Long_Bar_Row': 'Тяга конца грифа двумя руками в наклоне',
  'Bent_Over_Two-Dumbbell_Row': 'Тяга двух гантелей в наклоне',
  'Bent_Over_Two-Dumbbell_Row_With_Palms_In': 'Тяга двух гантелей в наклоне ладонями внутрь',
  'Bent_Press': 'Бент-пресс',
  'Bicycling': 'Езда на велосипеде',
  'Bicycling_Stationary': 'Велотренажер',
  'Board_Press': 'Жим штанги с доски',
  'Body-Up': 'Отжимания из упора на локтях',
  'Body_Tricep_Press': 'Разгибания рук на трицепс с собственным весом',
  'Bodyweight_Flyes': 'Разведение рук с собственным весом',
  'Bodyweight_Mid_Row': 'Австралийские подтягивания',
  'Bodyweight_Squat': 'Приседания с собственным весом',
  'Bodyweight_Walking_Lunge': 'Выпады при ходьбе без веса',
  'Bosu_Ball_Cable_Crunch_With_Side_Bends': 'Скручивания на блоке на BOSU с наклонами',
  'Bottoms-Up_Clean_From_The_Hang_Position': 'Взятие гири на грудь дном вверх с виса',
  'Bottoms_Up': 'Подъем ног и таза лежа',
  'Box_Jump_Multiple_Response': 'Повторные запрыгивания на тумбу',
  'Box_Skip': 'Быстрые зашагивания на тумбу',
  'Box_Squat': 'Приседания на тумбу',
  'Box_Squat_with_Bands': 'Приседания на тумбу с резиновыми петлями',
  'Box_Squat_with_Chains': 'Приседания на тумбу с цепями',
  'Brachialis-SMR': 'Плечевая мышца-СМР',
  'Bradford_Rocky_Presses': 'Жим Брэдфорда',
  'Butt-Ups': 'Подъем таза из упора лежа',
  'Butt_Lift_Bridge': 'Ягодичный мостик',
  'Butterfly': 'Сведение рук в тренажере «Бабочка»',
  'Cable_Chest_Press': 'Жим от груди на блоке',
  'Cable_Crossover': 'Сведение рук в кроссовере',
  'Cable_Crunch': 'Скручивания на блоке',
  'Cable_Deadlifts': 'Становая тяга на нижнем блоке',
  'Cable_Hammer_Curls_-_Rope_Attachment': 'Сгибание рук «Молот» на блоке с канатом',
  'Cable_Hip_Adduction': 'Приведение бедра на нижнем блоке',
  'Cable_Incline_Pushdown': 'Разгибания рук на блоке в наклоне',
  'Cable_Incline_Triceps_Extension': 'Разгибание рук на трицепс на блоке на наклонной скамье',
  'Cable_Internal_Rotation': 'Внутреннее вращение плеча на блоке',
  'Cable_Iron_Cross': 'Сведение рук «Железный крест» в кроссовере',
  'Cable_Judo_Flip': 'Бросок через плечо на блоке',
  'Cable_Lying_Triceps_Extension': 'Французский жим на блоке лежа',
  'Cable_One_Arm_Tricep_Extension': 'Разгибание одной руки на трицепс на блоке',
  'Cable_Preacher_Curl': 'Сгибание рук на блоке на скамье Скотта',
  'Cable_Rear_Delt_Fly': 'Разведение рук назад в кроссовере',
  'Cable_Reverse_Crunch': 'Обратные скручивания на нижнем блоке',
  'Cable_Rope_Overhead_Triceps_Extension': 'Разгибание рук на трицепс из-за головы с канатом',
  'Cable_Rope_Rear-Delt_Rows': 'Тяга на задние дельты с канатом',
  'Cable_Russian_Twists': 'Русский твист на блоке',
  'Cable_Seated_Crunch': 'Скручивания на блоке сидя',
  'Cable_Seated_Lateral_Raise': 'Махи в сторону сидя на блоке',
  'Cable_Shoulder_Press': 'Жим на плечи на блоке',
  'Cable_Shrugs': 'Шраги на блоке',
  'Cable_Wrist_Curl': 'Сгибание запястий на блоке',
  'Calf-Machine_Shoulder_Shrug': 'Шраги в тренажере для икр',
  'Calf_Press': 'Жим носками в тренажере',
  'Calf_Press_On_The_Leg_Press_Machine': 'Жим носками в жиме ногами',
  'Calf_Raise_On_A_Dumbbell': 'Подъем на носки с гантелью',
  'Calf_Raises_-_With_Bands': 'Подъем на носки с эспандером',
  'Calf_Stretch_Elbows_Against_Wall': 'Растяжка икроножных с упором локтями в стену',
  'Calf_Stretch_Hands_Against_Wall': 'Растяжка икроножных с упором руками в стену',
  'Calves-SMR': 'Икроножные-СМР',
  'Car_Deadlift': 'Становая тяга автомобиля',
  'Car_Drivers': 'Повороты диска перед собой',
  'Carioca_Quick_Step': 'Быстрый скрестный шаг (кариока)',
  'Cat_Stretch': 'Растяжка «Кошка»',
  'Catch_and_Overhead_Throw': 'Ловля и бросок медбола над головой',
  'Chain_Handle_Extension': 'Разгибание рук с цепями',
  'Chain_Press': 'Жим с цепями лежа',
  'Chair_Leg_Extended_Stretch': 'Растяжка задней поверхности бедра на стуле',
  'Chair_Lower_Back_Stretch': 'Растяжка поясницы на стуле',
  'Chair_Squat': 'Приседания на стул',
  'Chair_Upper_Body_Stretch': 'Растяжка верхней части тела на стуле',
  'Chest_And_Front_Of_Shoulder_Stretch': 'Растяжка груди и передней дельты',
  'Chest_Push_from_3_point_stance': 'Толчок медбола от груди из упора на трёх точках',
  'Chest_Push_multiple_response': 'Повторные толчки медбола от груди',
  'Chest_Push_single_response': 'Толчок медбола от груди',
  'Chest_Push_with_Run_Release': 'Толчок медбола от груди с переходом на бег',
  'Chest_Stretch_on_Stability_Ball': 'Растяжка груди на фитболе',
  'Childs_Pose': 'Поза ребёнка',
  'Chin-Up': 'Подтягивания обратным хватом',
  'Chin_To_Chest_Stretch': 'Растяжка шеи подбородком к груди',
  'Circus_Bell': 'Подъем цирковой гири',
  'Clean': 'Взятие на грудь',
  'Clean_Deadlift': 'Тяжелоатлетическая тяга',
  'Clean_Pull': 'Тяговая протяжка',
  'Clean_Shrug': 'Шраги тяжелоатлетические',
  'Clean_and_Jerk': 'Толчок штанги по длинному циклу',
  'Clean_and_Press': 'Взятие на грудь и жим',
  'Clean_from_Blocks': 'Взятие на грудь с плинтов',
  'Clock_Push-Up': 'Отжимания по кругу',
  'Close-Grip_Barbell_Bench_Press': 'Жим штанги лежа узким хватом',
  'Close-Grip_Dumbbell_Press': 'Жим гантелей лежа узким хватом',
  'Close-Grip_EZ-Bar_Curl_with_Band': 'Подъем EZ-штанги на бицепс узким хватом с эспандером',
  'Close-Grip_EZ-Bar_Press': 'Жим EZ-штанги лежа узким хватом',
  'Close-Grip_EZ_Bar_Curl': 'Подъем EZ-штанги на бицепс узким хватом',
  'Close-Grip_Front_Lat_Pulldown': 'Тяга верхнего блока к груди узким хватом',
  'Close-Grip_Push-Up_off_of_a_Dumbbell': 'Отжимания узким хватом от гантели',
  'Close-Grip_Standing_Barbell_Curl': 'Подъем штанги на бицепс узким хватом стоя',
  'Cocoons': 'Кокон (упражнение на пресс)',
  'Conans_Wheel': 'Колесо Конана',
  'Concentration_Curls': 'Концентрированные сгибания рук',
  'Cross-Body_Crunch': 'Косые скручивания',
  'Cross_Body_Hammer_Curl': 'Сгибание рук «Молот» поперек тела',
  'Cross_Over_-_With_Bands': 'Сведение рук с резиновыми петлями',
  'Crossover_Reverse_Lunge': 'Перекрестные выпады назад',
  'Crucifix': 'Распятие',
  'Crunch_-_Hands_Overhead': 'Скручивания с руками над головой',
  'Crunch_-_Legs_On_Exercise_Ball': 'Скручивания с ногами на фитболе',
  'Crunches': 'Скручивания',
  'Cuban_Press': 'Кубинский жим',
  'Dancers_Stretch': 'Растяжка танцора',
  'Dead_Bug': 'Мёртвый жук',
  'Deadlift_with_Bands': 'Становая тяга с резиновыми петлями',
  'Deadlift_with_Chains': 'Становая тяга с цепями',
  'Decline_Barbell_Bench_Press': 'Жим штанги лежа с наклоном вниз',
  'Decline_Close-Grip_Bench_To_Skull_Crusher': 'Жим лежа узким хватом переходящий во французский жим',
  'Decline_Crunch': 'Скручивания на скамье с наклоном вниз',
  'Decline_Dumbbell_Bench_Press': 'Жим гантелей лежа с наклоном вниз',
  'Decline_Dumbbell_Flyes': 'Разведение гантелей с наклоном вниз',
  'Decline_Dumbbell_Triceps_Extension': 'Французский жим с гантелями с наклоном вниз',
  'Decline_EZ_Bar_Triceps_Extension': 'Французский жим EZ-штангой с наклоном вниз',
  'Decline_Oblique_Crunch': 'Косые скручивания с наклоном вниз',
  'Decline_Push-Up': 'Отжимания головой вниз',
  'Decline_Reverse_Crunch': 'Обратные скручивания с наклоном вниз',
  'Decline_Smith_Press': 'Жим с наклоном вниз в тренажере Смита',
  'Deficit_Deadlift': 'Становая тяга с дефицитом',
  'Depth_Jump_Leap': 'Прыжок в глубину с последующим прыжком',
  'Dip_Machine': 'Тренажер для отжиманий на брусьях',
  'Dips_-_Chest_Version': 'Отжимания на брусьях (акцент на грудь)',
  'Dips_-_Triceps_Version': 'Отжимания на брусьях (акцент на трицепс)',
  'Donkey_Calf_Raises': 'Подъёмы на носки «осликом»',
  'Double_Kettlebell_Alternating_Hang_Clean': 'Поочередное взятие двух гирь на грудь с виса',
  'Double_Kettlebell_Jerk': 'Толчок двух гирь',
  'Double_Kettlebell_Push_Press': 'Швунг двух гирь',
  'Double_Kettlebell_Snatch': 'Рывок двух гирь',
  'Double_Kettlebell_Windmill': 'Мельница с двумя гирями',
  'Double_Leg_Butt_Kick': 'Захлест голени назад двумя ногами',
  'Downward_Facing_Balance': 'Собака мордой вниз с поднятой ногой',
  'Drag_Curl': 'Сгибание рук протяжкой',
  'Drop_Push': 'Отжимания со спрыгиванием',
  'Dumbbell_Alternate_Bicep_Curl': 'Поочередные сгибания рук с гантелями',
  'Dumbbell_Bench_Press': 'Жим гантелей лежа',
  'Dumbbell_Bench_Press_with_Neutral_Grip': 'Жим гантелей лежа нейтральным хватом',
  'Dumbbell_Bicep_Curl': 'Сгибания рук с гантелями',
  'Dumbbell_Clean': 'Взятие гантелей на грудь',
  'Dumbbell_Floor_Press': 'Жим гантелей с пола',
  'Dumbbell_Flyes': 'Разведение гантелей лежа',
  'Dumbbell_Incline_Row': 'Тяга гантелей лежа на наклонной скамье',
  'Dumbbell_Incline_Shoulder_Raise': 'Подъем гантелей перед собой на наклонной скамье',
  'Dumbbell_Lunges': 'Выпады с гантелями',
  'Dumbbell_Lying_One-Arm_Rear_Lateral_Raise': 'Подъем гантели одной рукой лежа на заднюю дельту',
  'Dumbbell_Lying_Pronation': 'Пронация кисти с гантелью лежа',
  'Dumbbell_Lying_Rear_Lateral_Raise': 'Подъем гантелей на заднюю дельту лежа',
  'Dumbbell_Lying_Supination': 'Супинация кисти с гантелью лежа',
  'Dumbbell_One-Arm_Shoulder_Press': 'Жим гантели одной рукой над головой',
  'Dumbbell_One-Arm_Triceps_Extension': 'Разгибание одной руки с гантелью из-за головы',
  'Dumbbell_One-Arm_Upright_Row': 'Тяга одной гантели к подбородку',
  'Dumbbell_Prone_Incline_Curl': 'Сгибания рук с гантелями лёжа на наклонной скамье лицом вниз',
  'Dumbbell_Raise': 'Подъем гантелей',
  'Dumbbell_Rear_Lunge': 'Выпады назад с гантелями',
  'Dumbbell_Scaption': 'Подъем гантелей в лопаточной плоскости',
  'Dumbbell_Seated_Box_Jump': 'Запрыгивание на тумбу сидя с гантелями',
  'Dumbbell_Seated_One-Leg_Calf_Raise': 'Подъем на носок одной ноги сидя с гантелью',
  'Dumbbell_Shoulder_Press': 'Жим гантелей сидя',
  'Dumbbell_Shrug': 'Шраги с гантелями',
  'Dumbbell_Side_Bend': 'Наклоны в стороны с гантелью',
  'Dumbbell_Squat': 'Приседания с гантелями',
  'Dumbbell_Squat_To_A_Bench': 'Приседания с гантелями на скамью',
  'Dumbbell_Step_Ups': 'Зашагивания на платформу с гантелями',
  'Dumbbell_Tricep_Extension_-Pronated_Grip': 'Разгибание рук с гантелями пронированным хватом',
  'Dynamic_Back_Stretch': 'Динамическая растяжка спины',
  'Dynamic_Chest_Stretch': 'Динамическая растяжка груди',
  'EZ-Bar_Curl': 'Сгибания рук с EZ-штангой',
  'EZ-Bar_Skullcrusher': 'Французский жим с EZ-штангой лежа',
  'Elbow_Circles': 'Вращения в локтевых суставах',
  'Elbow_to_Knee': 'Локоть к колену',
  'Elbows_Back': 'Отведение локтей назад',
  'Elevated_Back_Lunge': 'Выпады назад с возвышения',
  'Elevated_Cable_Rows': 'Тяга блока сверху',
  'Elliptical_Trainer': 'Эллиптический тренажер',
  'Exercise_Ball_Crunch': 'Скручивания на фитболе',
  'Exercise_Ball_Pull-In': 'Подтягивание коленей к груди на фитболе',
  'Extended_Range_One-Arm_Kettlebell_Floor_Press': 'Жим гири одной рукой с пола с увеличенной амплитудой',
  'External_Rotation': 'Внешняя ротация плеча',
  'External_Rotation_with_Band': 'Внешняя ротация плеча с амортизатором',
  'External_Rotation_with_Cable': 'Внешняя ротация плеча на блоке',
  'Face_Pull': 'Тяга к лицу на блоке',
  'Farmers_Walk': 'Прогулка фермера',
  'Fast_Skipping': 'Быстрые прыжки через скакалку',
  'Finger_Curls': 'Сгибания пальцев со штангой',
  'Flat_Bench_Cable_Flyes': 'Сведение рук на блоках лежа',
  'Flat_Bench_Leg_Pull-In': 'Подтягивание коленей к груди сидя на скамье',
  'Flat_Bench_Lying_Leg_Raise': 'Подъем ног лежа на горизонтальной скамье',
  'Flexor_Incline_Dumbbell_Curls': 'Сгибание запястий с гантелями на наклонной скамье',
  'Floor_Glute-Ham_Raise': 'Нордические сгибания на полу',
  'Floor_Press': 'Жим штанги с пола',
  'Floor_Press_with_Chains': 'Жим штанги с пола с цепями',
  'Flutter_Kicks': 'Ножницы',
  'Foot-SMR': 'Стопа-СМР',
  'Forward_Drag_with_Press': 'Тяга саней вперед с жимом',
  'Frankenstein_Squat': 'Приседания Франкенштейна',
  'Freehand_Jump_Squat': 'Выпрыгивания из приседа без отягощения',
  'Frog_Hops': 'Прыжки лягушкой',
  'Frog_Sit-Ups': 'Скручивания лягушка',
  'Front_Barbell_Squat': 'Фронтальные приседания со штангой',
  'Front_Barbell_Squat_To_A_Bench': 'Фронтальные приседания со штангой на скамью',
  'Front_Box_Jump': 'Запрыгивание на тумбу',
  'Front_Cable_Raise': 'Подъем рук перед собой на блоке',
  'Front_Cone_Hops_or_hurdle_hops': 'Прыжки вперед через барьеры',
  'Front_Dumbbell_Raise': 'Подъем гантелей перед собой',
  'Front_Incline_Dumbbell_Raise': 'Подъем гантелей перед собой на наклонной скамье',
  'Front_Leg_Raises': 'Подъемы ног перед собой',
  'Front_Plate_Raise': 'Подъем блина перед собой',
  'Front_Raise_And_Pullover': 'Подъем перед собой с переходом в пуловер',
  'Front_Squat_Clean_Grip': 'Фронтальный присед тяжелоатлетическим хватом',
  'Front_Squats_With_Two_Kettlebells': 'Фронтальные приседания с двумя гирями',
  'Front_Two-Dumbbell_Raise': 'Подъем двух гантелей перед собой',
  'Full_Range-Of-Motion_Lat_Pulldown': 'Тяга верхнего блока с полной амплитудой',
  'Gironda_Sternum_Chins': 'Подтягивания Жиронды к грудине',
  'Glute_Ham_Raise': 'Подъем корпуса на GHD-скамье',
  'Glute_Kickback': 'Махи ногой назад',
  'Goblet_Squat': 'Кубковые приседания',
  'Good_Morning': 'Наклоны «Доброе утро»',
  'Good_Morning_off_Pins': 'Наклоны «Доброе утро» с ограничителей',
  'Gorilla_Chin_Crunch': 'Подтягивания с подъемом коленей «Горилла»',
  'Groin_and_Back_Stretch': 'Растяжка паха и спины',
  'Groiners': 'Гройнеры',
  'Hack_Squat': 'Гакк-приседания',
  'Hammer_Curls': 'Сгибания рук «Молот»',
  'Hammer_Grip_Incline_DB_Bench_Press': 'Жим гантелей на наклонной скамье нейтральным хватом',
  'Hamstring-SMR': 'Задняя поверхность бедра-СМР',
  'Hamstring_Stretch': 'Растяжка задней поверхности бедра',
  'Handstand_Push-Ups': 'Отжимания в стойке на руках',
  'Hang_Clean': 'Взятие на грудь с виса',
  'Hang_Clean_-_Below_the_Knees': 'Взятие на грудь с виса ниже колен',
  'Hang_Snatch': 'Рывок с виса',
  'Hang_Snatch_-_Below_Knees': 'Рывок с виса ниже колен',
  'Hanging_Bar_Good_Morning': 'Наклоны со штангой на ремнях',
  'Hanging_Leg_Raise': 'Подъем ног в висе',
  'Hanging_Pike': 'Подъем ног к перекладине',
  'Heaving_Snatch_Balance': 'Рывковый баланс с выталкиванием',
  'Heavy_Bag_Thrust': 'Выталкивание тяжелого мешка',
  'High_Cable_Curls': 'Сгибания рук на верхних блоках',
  'Hip_Circles_prone': 'Круговые движения бедрами лежа',
  'Hip_Extension_with_Bands': 'Разгибание бедра с резиновой лентой',
  'Hip_Flexion_with_Band': 'Сгибание бедра с резиновой лентой',
  'Hip_Lift_with_Band': 'Ягодичный мостик с резиновой лентой',
  'Hug_A_Ball': 'Растяжка спины с фитболом',
  'Hug_Knees_To_Chest': 'Притягивание коленей к груди',
  'Hurdle_Hops': 'Прыжки через барьеры',
  'Hyperextensions_Back_Extensions': 'Гиперэкстензия',
  'Hyperextensions_With_No_Hyperextension_Bench': 'Гиперэкстензия на полу (лодочка)',
  'IT_Band_and_Glute_Stretch': 'Растяжка илиотибиального тракта и ягодиц',
  'Iliotibial_Tract-SMR': 'Илиотибиальный тракт-СМР',
  'Inchworm': 'Гусеница',
  'Incline_Barbell_Triceps_Extension': 'Французский жим со штангой на наклонной скамье',
  'Incline_Bench_Pull': 'Тяга штанги лежа на наклонной скамье',
  'Incline_Cable_Chest_Press': 'Жим на блоках лежа на наклонной скамье',
  'Incline_Cable_Flye': 'Сведение рук на блоках на наклонной скамье',
  'Incline_Dumbbell_Bench_With_Palms_Facing_In': 'Жим гантелей на наклонной скамье ладонями внутрь',
  'Incline_Dumbbell_Curl': 'Сгибания рук с гантелями на наклонной скамье',
  'Incline_Dumbbell_Flyes': 'Разведение гантелей на наклонной скамье',
  'Incline_Dumbbell_Flyes_-_With_A_Twist': 'Разведение гантелей на наклонной скамье с разворотом',
  'Incline_Dumbbell_Press': 'Жим гантелей на наклонной скамье',
  'Incline_Hammer_Curls': 'Сгибания рук «Молот» на наклонной скамье',
  'Incline_Inner_Biceps_Curl': 'Сгибания на внутренний пучок бицепса на наклонной скамье',
  'Incline_Push-Up': 'Отжимания от возвышения',
  'Incline_Push-Up_Close-Grip': 'Отжимания от возвышения узким хватом',
  'Incline_Push-Up_Depth_Jump': 'Плиометрические отжимания от возвышения',
  'Incline_Push-Up_Medium': 'Отжимания от возвышения средним хватом',
  'Incline_Push-Up_Reverse_Grip': 'Отжимания от возвышения обратным хватом',
  'Incline_Push-Up_Wide': 'Отжимания от возвышения широким хватом',
  'Intermediate_Groin_Stretch': 'Растяжка паха среднего уровня',
  'Intermediate_Hip_Flexor_and_Quad_Stretch': 'Растяжка сгибателей бедра и квадрицепсов',
  'Internal_Rotation_with_Band': 'Внутренняя ротация плеча с резиновой петлей',
  'Inverted_Row': 'Австралийские подтягивания',
  'Inverted_Row_with_Straps': 'Австралийские подтягивания на петлях',
  'Iron_Cross': 'Железный крест',
  'Iron_Crosses_stretch': 'Растяжка «Железный крест»',
  'Isometric_Chest_Squeezes': 'Изометрическое сжатие грудных мышц',
  'Isometric_Neck_Exercise_-_Front_And_Back': 'Изометрическое упражнение для шеи вперед-назад',
  'Isometric_Neck_Exercise_-_Sides': 'Изометрическое упражнение для шеи в стороны',
  'Isometric_Wipers': 'Изометрические дворники',
  'JM_Press': 'Жим JM',
  'Jackknife_Sit-Up': 'Скручивания «Книжка»',
  'Janda_Sit-Up': 'Скручивания Янда',
  'Jefferson_Squats': 'Приседания Джефферсона',
  'Jerk_Balance': 'Толчковый баланс',
  'Jerk_Dip_Squat': 'Толчковый полуприсед',
  'Jogging_Treadmill': 'Бег трусцой на беговой дорожке',
  'Keg_Load': 'Подъем бочонка',
  'Kettlebell_Arnold_Press': 'Жим Арнольда с гирей',
  'Kettlebell_Dead_Clean': 'Взятие гири на грудь с пола',
  'Kettlebell_Figure_8': 'Восьмерка с гирей',
  'Kettlebell_Hang_Clean': 'Взятие гири на грудь с виса',
  'Kettlebell_One-Legged_Deadlift': 'Становая тяга с гирей на одной ноге',
  'Kettlebell_Pass_Between_The_Legs': 'Передача гири между ногами',
  'Kettlebell_Pirate_Ships': 'Махи гирей из стороны в сторону',
  'Kettlebell_Pistol_Squat': 'Приседание «пистолетик» с гирей',
  'Kettlebell_Seated_Press': 'Жим гири сидя',
  'Kettlebell_Seesaw_Press': 'Поочередный жим гирь',
  'Kettlebell_Sumo_High_Pull': 'Тяга сумо к подбородку с гирей',
  'Kettlebell_Thruster': 'Трастеры с гирей',
  'Kettlebell_Turkish_Get-Up_Lunge_style': 'Турецкий подъем с гирей через выпад',
  'Kettlebell_Turkish_Get-Up_Squat_style': 'Турецкий подъем с гирей через присед',
  'Kettlebell_Windmill': 'Мельница с гирей',
  'Kipping_Muscle_Up': 'Выход силой с киппингом',
  'Knee_Across_The_Body': 'Подтягивание колена к противоположному плечу',
  'Knee_Circles': 'Вращения коленями',
  'Knee_Hip_Raise_On_Parallel_Bars': 'Подъем коленей на брусьях',
  'Knee_Tuck_Jump': 'Прыжки с подтягиванием коленей к груди',
  'Kneeling_Arm_Drill': 'Работа руками на коленях',
  'Kneeling_Cable_Crunch_With_Alternating_Oblique_Twists': 'Скручивания на блоке на коленях с поворотами',
  'Kneeling_Cable_Triceps_Extension': 'Разгибание рук на трицепс на блоке стоя на коленях',
  'Kneeling_Forearm_Stretch': 'Растяжка предплечий стоя на коленях',
  'Kneeling_High_Pulley_Row': 'Тяга с верхнего блока стоя на коленях',
  'Kneeling_Hip_Flexor': 'Растяжка сгибателей бедра на коленях',
  'Kneeling_Jump_Squat': 'Выпрыгивания из положения на коленях',
  'Kneeling_Single-Arm_High_Pulley_Row': 'Тяга одной рукой с верхнего блока на коленях',
  'Kneeling_Squat': 'Приседания на коленях',
  'Landmine_180s': 'Повороты корпуса с Т-грифом',
  'Landmine_Linear_Jammer': 'Жим Т-грифа перед собой',
  'Lateral_Bound': 'Боковые прыжки в сторону',
  'Lateral_Box_Jump': 'Боковые прыжки на тумбу',
  'Lateral_Cone_Hops': 'Боковые прыжки через конусы',
  'Lateral_Raise_-_With_Bands': 'Разведения рук в стороны с резиновой петлей',
  'Latissimus_Dorsi-SMR': 'Широчайшие мышцы-СМР',
  'Leg-Over_Floor_Press': 'Жим на полу с закинутой ногой',
  'Leg-Up_Hamstring_Stretch': 'Растяжка задней поверхности бедра с поднятой ногой',
  'Leg_Extensions': 'Разгибание ног в тренажере',
  'Leg_Lift': 'Подъем ног',
  'Leg_Press': 'Жим ногами',
  'Leg_Pull-In': 'Подтягивание коленей к груди сидя',
  'Leverage_Chest_Press': 'Жим от груди в рычажном тренажере',
  'Leverage_Deadlift': 'Становая тяга в рычажном тренажере',
  'Leverage_Decline_Chest_Press': 'Жим от груди с наклоном вниз в рычажном тренажере',
  'Leverage_High_Row': 'Вертикальная тяга в рычажном тренажере',
  'Leverage_Incline_Chest_Press': 'Жим от груди с наклоном вверх в рычажном тренажере',
  'Leverage_Iso_Row': 'Рычажная тяга одной рукой',
  'Leverage_Shoulder_Press': 'Жим на плечи в рычажном тренажере',
  'Leverage_Shrug': 'Шраги в рычажном тренажере',
  'Linear_3-Part_Start_Technique': 'Техника линейного старта в три части',
  'Linear_Acceleration_Wall_Drill': 'Упражнение у стены на линейное ускорение',
  'Linear_Depth_Jump': 'Глубинные прыжки вперед',
  'Log_Lift': 'Подъем бревна',
  'London_Bridges': 'Лондонский мост',
  'Looking_At_Ceiling': 'Наклон головы назад',
  'Low_Cable_Crossover': 'Сведение рук на нижних блоках кроссовера',
  'Low_Cable_Triceps_Extension': 'Разгибание рук на трицепс с нижнего блока',
  'Low_Pulley_Row_To_Neck': 'Тяга с нижнего блока к шее',
  'Lower_Back-SMR': 'Поясница-СМР',
  'Lower_Back_Curl': 'Разгибание поясницы',
  'Lunge_Pass_Through': 'Выпады с передачей снаряда под ногой',
  'Lunge_Sprint': 'Спринт из выпада',
  'Lying_Bent_Leg_Groin': 'Растяжка паха лежа с согнутой ногой',
  'Lying_Cable_Curl': 'Сгибание рук на бицепс лежа на блоке',
  'Lying_Cambered_Barbell_Row': 'Тяга изогнутой штанги лежа на скамье',
  'Lying_Close-Grip_Bar_Curl_On_High_Pulley': 'Сгибание рук узким хватом лежа на верхнем блоке',
  'Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head': 'Французский жим штанги лежа из-за головы',
  'Lying_Close-Grip_Barbell_Triceps_Press_To_Chin': 'Французский жим штанги лежа к подбородку',
  'Lying_Crossover': 'Сведение рук в кроссовере лежа',
  'Lying_Dumbbell_Tricep_Extension': 'Французский жим с гантелями лежа',
  'Lying_Face_Down_Plate_Neck_Resistance': 'Подъем головы лежа на животе с диском на затылке',
  'Lying_Face_Up_Plate_Neck_Resistance': 'Подъем головы лежа на спине с диском на лбу',
  'Lying_Glute': 'Растяжка ягодиц лежа',
  'Lying_Hamstring': 'Растяжка задней поверхности бедра лежа',
  'Lying_High_Bench_Barbell_Curl': 'Сгибание рук со штангой лежа на высокой скамье',
  'Lying_Leg_Curls': 'Сгибание ног лежа в тренажере',
  'Lying_Machine_Squat': 'Приседания в тренажере лежа',
  'Lying_One-Arm_Lateral_Raise': 'Махи одной рукой в сторону лежа на боку',
  'Lying_Prone_Quadriceps': 'Растяжка квадрицепсов лежа на животе',
  'Lying_Rear_Delt_Raise': 'Разведение гантелей на задние дельты лежа',
  'Lying_Supine_Dumbbell_Curl': 'Сгибание рук с гантелями лежа на спине',
  'Lying_T-Bar_Row': 'Тяга Т-грифа лежа на скамье',
  'Lying_Triceps_Press': 'Французский жим штанги лежа',
  'Machine_Bench_Press': 'Жим лежа в тренажере',
  'Machine_Bicep_Curl': 'Сгибание рук на бицепс в тренажере',
  'Machine_Preacher_Curls': 'Сгибание рук на бицепс в тренажере Скотта',
  'Machine_Shoulder_Military_Press': 'Жим на плечи в тренажере',
  'Machine_Triceps_Extension': 'Разгибание рук на трицепс в тренажере',
  'Medicine_Ball_Chest_Pass': 'Бросок медбола от груди',
  'Medicine_Ball_Full_Twist': 'Повороты корпуса с медболом',
  'Medicine_Ball_Scoop_Throw': 'Бросок медбола снизу',
  'Middle_Back_Shrug': 'Шраги назад на среднюю трапецию',
  'Middle_Back_Stretch': 'Растяжка средней части спины',
  'Mixed_Grip_Chin': 'Подтягивания разнохватом',
  'Monster_Walk': 'Прогулка монстра с резинкой',
  'Mountain_Climbers': 'Альпинист',
  'Moving_Claw_Series': 'Беговое упражнение «Когти» в движении',
  'Muscle_Snatch': 'Силовой рывок',
  'Muscle_Up': 'Выход силой',
  'Narrow_Stance_Hack_Squats': 'Гакк-приседания с узкой постановкой ног',
  'Narrow_Stance_Leg_Press': 'Жим ногами с узкой постановкой',
  'Narrow_Stance_Squats': 'Приседания с узкой постановкой ног',
  'Natural_Glute_Ham_Raise': 'Нордические сгибания ног',
  'Neck-SMR': 'Шея-СМР',
  'Neck_Press': 'Жим штанги к шее',
  'Oblique_Crunches': 'Косые скручивания',
  'Oblique_Crunches_-_On_The_Floor': 'Косые скручивания на полу',
  'Olympic_Squat': 'Олимпийские приседания',
  'On-Your-Back_Quad_Stretch': 'Растяжка квадрицепсов лежа на спине',
  'On_Your_Side_Quad_Stretch': 'Растяжка квадрицепсов лежа на боку',
  'One-Arm_Dumbbell_Row': 'Тяга гантели одной рукой в наклоне',
  'One-Arm_Flat_Bench_Dumbbell_Flye': 'Разведение одной рукой с гантелью лежа',
  'One-Arm_High-Pulley_Cable_Side_Bends': 'Наклоны в сторону на блоке одной рукой',
  'One-Arm_Incline_Lateral_Raise': 'Мах одной рукой в сторону на наклонной скамье',
  'One-Arm_Kettlebell_Clean': 'Взятие гири на грудь одной рукой',
  'One-Arm_Kettlebell_Clean_and_Jerk': 'Толчок гири одной рукой по длинному циклу',
  'One-Arm_Kettlebell_Floor_Press': 'Жим гири одной рукой с пола',
  'One-Arm_Kettlebell_Jerk': 'Толчок гири одной рукой',
  'One-Arm_Kettlebell_Military_Press_To_The_Side': 'Армейский жим гири в сторону',
  'One-Arm_Kettlebell_Para_Press': 'Жим гири одной рукой сбоку',
  'One-Arm_Kettlebell_Push_Press': 'Швунг гири одной рукой',
  'One-Arm_Kettlebell_Row': 'Тяга гири одной рукой в наклоне',
  'One-Arm_Kettlebell_Snatch': 'Рывок гири одной рукой',
  'One-Arm_Kettlebell_Split_Jerk': 'Толчок гири одной рукой в ножницы',
  'One-Arm_Kettlebell_Split_Snatch': 'Рывок гири одной рукой в ножницы',
  'One-Arm_Kettlebell_Swings': 'Махи гирей одной рукой',
  'One-Arm_Long_Bar_Row': 'Тяга конца грифа одной рукой',
  'One-Arm_Medicine_Ball_Slam': 'Удар медбола о пол одной рукой',
  'One-Arm_Open_Palm_Kettlebell_Clean': 'Взятие гири на грудь одной рукой на открытой ладони',
  'One-Arm_Overhead_Kettlebell_Squats': 'Приседания с гирей над головой одной рукой',
  'One-Arm_Side_Deadlift': 'Боковая становая тяга одной рукой',
  'One-Arm_Side_Laterals': 'Махи в сторону одной рукой',
  'One-Legged_Cable_Kickback': 'Махи ногой назад на нижнем блоке',
  'One_Arm_Against_Wall': 'Растяжка груди у стены одной рукой',
  'One_Arm_Chin-Up': 'Подтягивания на одной руке обратным хватом',
  'One_Arm_Dumbbell_Bench_Press': 'Жим гантели одной рукой лежа',
  'One_Arm_Dumbbell_Preacher_Curl': 'Сгибание одной руки с гантелью на скамье Скотта',
  'One_Arm_Floor_Press': 'Жим одной рукой лежа на полу',
  'One_Arm_Lat_Pulldown': 'Тяга верхнего блока одной рукой',
  'One_Arm_Pronated_Dumbbell_Triceps_Extension': 'Разгибание одной руки с гантелью из-за головы хватом сверху',
  'One_Arm_Supinated_Dumbbell_Triceps_Extension': 'Разгибание одной руки с гантелью из-за головы хватом снизу',
  'One_Half_Locust': 'Половина позы саранчи',
  'One_Handed_Hang': 'Вис на одной руке',
  'One_Knee_To_Chest': 'Подтягивание одного колена к груди',
  'One_Leg_Barbell_Squat': 'Приседания на одной ноге со штангой',
  'Open_Palm_Kettlebell_Clean': 'Взятие гири на грудь на открытой ладони',
  'Otis-Up': 'Подъем корпуса Отиса',
  'Overhead_Cable_Curl': 'Сгибание рук с верхних блоков',
  'Overhead_Lat': 'Растяжка широчайших над головой',
  'Overhead_Slam': 'Удар медбола о пол из-за головы',
  'Overhead_Squat': 'Приседания со штангой над головой',
  'Overhead_Stretch': 'Растяжка над головой',
  'Overhead_Triceps': 'Растяжка трицепсов над головой',
  'Pallof_Press': 'Жим Паллофа',
  'Pallof_Press_With_Rotation': 'Жим Паллофа с вращением',
  'Palms-Down_Dumbbell_Wrist_Curl_Over_A_Bench': 'Разгибания запястий с гантелями на скамье хватом сверху',
  'Palms-Down_Wrist_Curl_Over_A_Bench': 'Разгибания запястий на скамье хватом сверху',
  'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench': 'Сгибания запястий со штангой на скамье хватом снизу',
  'Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench': 'Сгибания запястий с гантелями на скамье хватом снизу',
  'Parallel_Bar_Dip': 'Отжимания на брусьях',
  'Pelvic_Tilt_Into_Bridge': 'Подъем таза в ягодичный мостик',
  'Peroneals-SMR': 'Малоберцовые мышцы-СМР',
  'Peroneals_Stretch': 'Растяжка малоберцовых мышц',
  'Physioball_Hip_Bridge': 'Ягодичный мостик на фитболе',
  'Pin_Presses': 'Жим штанги с ограничителей',
  'Piriformis-SMR': 'Грушевидная мышца-СМР',
  'Plank': 'Планка',
  'Plate_Pinch': 'Щипковый хват блина',
  'Plate_Twist': 'Повороты корпуса с блином',
  'Platform_Hamstring_Slides': 'Сгибания ног на скользящей платформе',
  'Plie_Dumbbell_Squat': 'Приседания плие с гантелью',
  'Plyo_Kettlebell_Pushups': 'Плиометрические отжимания на гирях',
  'Plyo_Push-up': 'Плиометрические отжимания',
  'Posterior_Tibialis_Stretch': 'Растяжка задней большеберцовой мышцы',
  'Power_Clean': 'Взятие штанги на грудь в полуприсед',
  'Power_Clean_from_Blocks': 'Взятие штанги на грудь с плинтов в полуприсед',
  'Power_Jerk': 'Швунг толчковый',
  'Power_Partials': 'Частичные подъемы гантелей в стороны',
  'Power_Snatch': 'Рывок в полуприсед',
  'Power_Snatch_from_Blocks': 'Рывок с плинтов в полуприсед',
  'Power_Stairs': 'Силовая лестница',
  'Preacher_Curl': 'Сгибания рук на скамье Скотта',
  'Preacher_Hammer_Dumbbell_Curl': 'Сгибания «Молот» на скамье Скотта',
  'Press_Sit-Up': 'Ситап с жимом вверх',
  'Prone_Manual_Hamstring': 'Сгибания ног лежа с сопротивлением',
  'Prowler_Sprint': 'Толкание саней Prowler',
  'Pull_Through': 'Тяга через ноги на нижнем блоке',
  'Pullups': 'Подтягивания',
  'Push-Up_Wide': 'Отжимания широким хватом',
  'Push-Ups_-_Close_Triceps_Position': 'Отжимания узким хватом на трицепс',
  'Push-Ups_With_Feet_Elevated': 'Отжимания с ногами на возвышении',
  'Push-Ups_With_Feet_On_An_Exercise_Ball': 'Отжимания с ногами на фитболе',
  'Push_Press': 'Швунг жимовой',
  'Push_Press_-_Behind_the_Neck': 'Швунг жимовой из-за головы',
  'Push_Up_to_Side_Plank': 'Отжимания с переходом в боковую планку',
  'Pushups': 'Отжимания',
  'Pushups_Close_and_Wide_Hand_Positions': 'Отжимания узкой и широкой постановкой рук',
  'Pyramid': 'Пирамида',
  'Quad_Stretch': 'Растяжка квадрицепсов',
  'Quadriceps-SMR': 'Квадрицепсы-СМР',
  'Quick_Leap': 'Быстрый прыжок',
  'Rack_Delivery': 'Прием штанги на грудь после подрыва',
  'Rack_Pull_with_Bands': 'Тяга с плинтов с резиновыми петлями',
  'Rack_Pulls': 'Тяга с плинтов',
  'Rear_Leg_Raises': 'Махи ногой назад',
  'Recumbent_Bike': 'Горизонтальный велотренажер',
  'Return_Push_from_Stance': 'Возвратный толчок из стойки',
  'Reverse_Band_Bench_Press': 'Жим штанги лежа с облегчающими петлями',
  'Reverse_Band_Box_Squat': 'Приседания на тумбу с облегчающими петлями',
  'Reverse_Band_Deadlift': 'Становая тяга с облегчающими петлями',
  'Reverse_Band_Power_Squat': 'Силовые приседания с облегчающими петлями',
  'Reverse_Band_Sumo_Deadlift': 'Становая тяга сумо с облегчающими петлями',
  'Reverse_Barbell_Curl': 'Сгибания рук со штангой обратным хватом',
  'Reverse_Barbell_Preacher_Curls': 'Сгибания рук со штангой обратным хватом на скамье Скотта',
  'Reverse_Cable_Curl': 'Сгибания рук на блоке обратным хватом',
  'Reverse_Crunch': 'Обратные скручивания',
  'Reverse_Flyes': 'Обратные разведения рук',
  'Reverse_Flyes_With_External_Rotation': 'Обратные разведения рук с разворотом наружу',
  'Reverse_Grip_Bent-Over_Rows': 'Тяга штанги в наклоне обратным хватом',
  'Reverse_Grip_Triceps_Pushdown': 'Разгибания рук на блоке обратным хватом',
  'Reverse_Hyperextension': 'Обратная гиперэкстензия',
  'Reverse_Machine_Flyes': 'Обратные разведения в тренажере',
  'Reverse_Plate_Curls': 'Сгибания рук с блином обратным хватом',
  'Reverse_Triceps_Bench_Press': 'Жим штанги лежа обратным хватом',
  'Rhomboids-SMR': 'Ромбовидные мышцы-СМР',
  'Rickshaw_Carry': 'Переноска рамы «Рикша»',
  'Rickshaw_Deadlift': 'Становая тяга с рамой «Рикша»',
  'Ring_Dips': 'Отжимания на кольцах',
  'Rocket_Jump': 'Прыжок «Ракета»',
  'Rocking_Standing_Calf_Raise': 'Подъемы на носки перекатом стоя',
  'Rocky_Pull-Ups_Pulldowns': 'Подтягивания в стиле Рокки',
  'Romanian_Deadlift': 'Румынская становая тяга',
  'Romanian_Deadlift_from_Deficit': 'Румынская тяга с дефицитом',
  'Rope_Climb': 'Подъем по канату',
  'Rope_Crunch': 'Скручивания на блоке с канатом',
  'Rope_Jumping': 'Прыжки через скакалку',
  'Rope_Straight-Arm_Pulldown': 'Тяга сверху прямыми руками с канатом',
  'Round_The_World_Shoulder_Stretch': 'Круговая растяжка плеч',
  'Rowing_Stationary': 'Гребной тренажер',
  'Runners_Stretch': 'Растяжка бегуна',
  'Running_Treadmill': 'Бег на беговой дорожке',
  'Russian_Twist': 'Русский твист',
  'Sandbag_Load': 'Погрузка мешка с песком',
  'Scapular_Pull-Up': 'Лопаточные подтягивания',
  'Scissor_Kick': 'Ножницы ногами',
  'Scissors_Jump': 'Прыжки со сменой ног',
  'Seated_Band_Hamstring_Curl': 'Сгибания ног сидя с резиновой петлей',
  'Seated_Barbell_Military_Press': 'Армейский жим штанги сидя',
  'Seated_Barbell_Twist': 'Повороты корпуса со штангой сидя',
  'Seated_Bent-Over_One-Arm_Dumbbell_Triceps_Extension': 'Разгибание одной руки с гантелью в наклоне сидя',
  'Seated_Bent-Over_Rear_Delt_Raise': 'Разведения гантелей в наклоне сидя',
  'Seated_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension': 'Разгибания рук с гантелями в наклоне сидя',
  'Seated_Biceps': 'Сгибания рук на бицепс сидя',
  'Seated_Cable_Rows': 'Тяга горизонтального блока сидя',
  'Seated_Cable_Shoulder_Press': 'Жим на плечи на блоке сидя',
  'Seated_Calf_Raise': 'Подъемы на носки сидя',
  'Seated_Calf_Stretch': 'Растяжка икроножных мышц сидя',
  'Seated_Close-Grip_Concentration_Barbell_Curl': 'Концентрированные сгибания со штангой узким хватом сидя',
  'Seated_Dumbbell_Curl': 'Сгибания рук с гантелями сидя',
  'Seated_Dumbbell_Inner_Biceps_Curl': 'Сгибания рук с гантелями на внутренний пучок бицепса',
  'Seated_Dumbbell_Palms-Down_Wrist_Curl': 'Разгибания запястий с гантелями сидя',
  'Seated_Dumbbell_Palms-Up_Wrist_Curl': 'Сгибания запястий с гантелями сидя',
  'Seated_Dumbbell_Press': 'Жим гантелей сидя',
  'Seated_Flat_Bench_Leg_Pull-In': 'Подтягивание ног к себе сидя на скамье',
  'Seated_Floor_Hamstring_Stretch': 'Растяжка задней поверхности бедра сидя на полу',
  'Seated_Front_Deltoid': 'Растяжка передней дельты сидя',
  'Seated_Glute': 'Растяжка ягодиц сидя',
  'Seated_Good_Mornings': 'Наклоны «Доброе утро» сидя',
  'Seated_Hamstring': 'Растяжка задней поверхности бедра сидя',
  'Seated_Hamstring_and_Calf_Stretch': 'Растяжка задней поверхности бедра и икроножных сидя',
  'Seated_Head_Harness_Neck_Resistance': 'Разгибания шеи сидя с упряжью',
  'Seated_Leg_Curl': 'Сгибания ног в тренажере сидя',
  'Seated_Leg_Tucks': 'Сгибания ног к себе сидя',
  'Seated_One-Arm_Dumbbell_Palms-Down_Wrist_Curl': 'Разгибание одного запястья с гантелью сидя',
  'Seated_One-Arm_Dumbbell_Palms-Up_Wrist_Curl': 'Сгибание одного запястья с гантелью сидя',
  'Seated_One-arm_Cable_Pulley_Rows': 'Тяга блока одной рукой сидя',
  'Seated_Overhead_Stretch': 'Растяжка рук над головой сидя',
  'Seated_Palm-Up_Barbell_Wrist_Curl': 'Сгибания запястий со штангой сидя',
  'Seated_Palms-Down_Barbell_Wrist_Curl': 'Разгибания запястий со штангой сидя',
  'Seated_Side_Lateral_Raise': 'Махи гантелями в стороны сидя',
  'Seated_Triceps_Press': 'Разгибания рук на трицепс сидя',
  'Seated_Two-Arm_Palms-Up_Low-Pulley_Wrist_Curl': 'Сгибания запястий на нижнем блоке сидя',
  'See-Saw_Press_Alternating_Side_Press': 'Поочередный жим гантелей «Пила»',
  'Shotgun_Row': 'Тяга «Дробовик» на нижнем блоке',
  'Shoulder_Circles': 'Вращения плечами',
  'Shoulder_Press_-_With_Bands': 'Жим над головой с резиновыми петлями',
  'Shoulder_Raise': 'Подъемы рук',
  'Shoulder_Stretch': 'Растяжка плеч',
  'Side-Lying_Floor_Stretch': 'Растяжка лежа на боку',
  'Side_Bridge': 'Боковая планка',
  'Side_Hop-Sprint': 'Боковой прыжок со спринтом',
  'Side_Jackknife': 'Боковая складка',
  'Side_Lateral_Raise': 'Махи гантелями в стороны стоя',
  'Side_Laterals_to_Front_Raise': 'Махи в стороны с переходом в подъем перед собой',
  'Side_Leg_Raises': 'Махи ногами в стороны',
  'Side_Lying_Groin_Stretch': 'Растяжка паха лежа на боку',
  'Side_Neck_Stretch': 'Боковая растяжка шеи',
  'Side_Standing_Long_Jump': 'Прыжок в длину боком с места',
  'Side_To_Side_Chins': 'Подтягивания из стороны в сторону',
  'Side_Wrist_Pull': 'Боковое растяжение запястья',
  'Side_to_Side_Box_Shuffle': 'Перемещения в стороны через тумбу',
  'Single-Arm_Cable_Crossover': 'Сведение одной руки в кроссовере',
  'Single-Arm_Linear_Jammer': 'Жим одной рукой в тренажере',
  'Single-Arm_Push-Up': 'Отжимания на одной руке',
  'Single-Cone_Sprint_Drill': 'Спринт вокруг конуса',
  'Single-Leg_High_Box_Squat': 'Приседания на одной ноге на высокую тумбу',
  'Single-Leg_Hop_Progression': 'Прыжки на одной ноге в прогрессии',
  'Single-Leg_Lateral_Hop': 'Боковые прыжки на одной ноге',
  'Single-Leg_Leg_Extension': 'Разгибания одной ноги в тренажере',
  'Single-Leg_Stride_Jump': 'Шаговый прыжок на одной ноге',
  'Single_Dumbbell_Raise': 'Подъем одной гантели',
  'Single_Leg_Butt_Kick': 'Захлестывание голени одной ноги',
  'Single_Leg_Glute_Bridge': 'Ягодичный мостик на одной ноге',
  'Single_Leg_Push-off': 'Отталкивание одной ногой',
  'Sit-Up': 'Ситап',
  'Sit_Squats': 'Приседания на тумбу',
  'Skating': 'Конькобежец',
  'Sled_Drag_-_Harness': 'Тяга саней в упряжке',
  'Sled_Overhead_Backward_Walk': 'Ходьба назад с тягой саней над головой',
  'Sled_Overhead_Triceps_Extension': 'Разгибания на трицепс над головой с санями',
  'Sled_Push': 'Толкание саней',
  'Sled_Reverse_Flye': 'Обратные разведения с санями',
  'Sled_Row': 'Тяга саней к себе',
  'Sledgehammer_Swings': 'Удары кувалдой',
  'Smith_Incline_Shoulder_Raise': 'Шраги на наклонной в тренажере Смита',
  'Smith_Machine_Behind_the_Back_Shrug': 'Шраги из-за спины в тренажере Смита',
  'Smith_Machine_Bench_Press': 'Жим лежа в тренажере Смита',
  'Smith_Machine_Bent_Over_Row': 'Тяга в наклоне в тренажере Смита',
  'Smith_Machine_Calf_Raise': 'Подъем на носки в тренажере Смита',
  'Smith_Machine_Close-Grip_Bench_Press': 'Жим лежа узким хватом в тренажере Смита',
  'Smith_Machine_Decline_Press': 'Жим с наклоном вниз в тренажере Смита',
  'Smith_Machine_Hang_Power_Clean': 'Взятие на грудь с виса в тренажере Смита',
  'Smith_Machine_Hip_Raise': 'Подъем таза в тренажере Смита',
  'Smith_Machine_Incline_Bench_Press': 'Жим на наклонной скамье в тренажере Смита',
  'Smith_Machine_Leg_Press': 'Жим ногами в тренажере Смита',
  'Smith_Machine_One-Arm_Upright_Row': 'Тяга к подбородку одной рукой в тренажере Смита',
  'Smith_Machine_Overhead_Shoulder_Press': 'Жим над головой в тренажере Смита',
  'Smith_Machine_Pistol_Squat': 'Приседания «пистолетик» в тренажере Смита',
  'Smith_Machine_Reverse_Calf_Raises': 'Обратные подъемы на носки в тренажере Смита',
  'Smith_Machine_Squat': 'Приседания в тренажере Смита',
  'Smith_Machine_Stiff-Legged_Deadlift': 'Румынская тяга в тренажере Смита',
  'Smith_Machine_Upright_Row': 'Тяга к подбородку в тренажере Смита',
  'Smith_Single-Leg_Split_Squat': 'Болгарские сплит-приседания в тренажере Смита',
  'Snatch': 'Рывок',
  'Snatch_Balance': 'Рывковый баланс',
  'Snatch_Deadlift': 'Рывковая тяга',
  'Snatch_Pull': 'Рывковая протяжка',
  'Snatch_Shrug': 'Шраги рывковым хватом',
  'Snatch_from_Blocks': 'Рывок с плинтов',
  'Speed_Band_Overhead_Triceps': 'Скоростные разгибания трицепса с амортизатором над головой',
  'Speed_Box_Squat': 'Скоростные приседания на тумбу',
  'Speed_Squats': 'Скоростные приседания',
  'Spell_Caster': 'Маятник с диском',
  'Spider_Crawl': 'Паучий шаг',
  'Spider_Curl': 'Паучьи сгибания рук',
  'Spinal_Stretch': 'Растяжка позвоночника',
  'Split_Clean': 'Взятие на грудь в ножницы',
  'Split_Jerk': 'Толчок в ножницы',
  'Split_Jump': 'Прыжки со сменой ног',
  'Split_Snatch': 'Рывок в ножницы',
  'Split_Squat_with_Dumbbells': 'Сплит-приседания с гантелями',
  'Split_Squats': 'Сплит-приседания',
  'Squat_Jerk': 'Толчок в сед',
  'Squat_with_Bands': 'Приседания с амортизатором',
  'Squat_with_Chains': 'Приседания с цепями',
  'Squat_with_Plate_Movers': 'Приседания с движением дисков',
  'Squats_-_With_Bands': 'Приседания с амортизатором',
  'Stairmaster': 'Степпер',
  'Standing_Alternating_Dumbbell_Press': 'Поочередный жим гантелей стоя',
  'Standing_Barbell_Calf_Raise': 'Подъемы на носки со штангой стоя',
  'Standing_Barbell_Press_Behind_Neck': 'Жим штанги из-за головы стоя',
  'Standing_Bent-Over_One-Arm_Dumbbell_Triceps_Extension': 'Разгибание одной руки с гантелью в наклоне стоя',
  'Standing_Bent-Over_Two-Arm_Dumbbell_Triceps_Extension': 'Разгибание рук с гантелями в наклоне стоя',
  'Standing_Biceps_Cable_Curl': 'Сгибание рук на бицепс на нижнем блоке стоя',
  'Standing_Biceps_Stretch': 'Растяжка бицепса стоя',
  'Standing_Bradford_Press': 'Жим Брэдфорда стоя',
  'Standing_Cable_Chest_Press': 'Жим от груди на блоке стоя',
  'Standing_Cable_Lift': 'Тяга блока снизу вверх по диагонали',
  'Standing_Cable_Wood_Chop': 'Дровосек на блоке стоя',
  'Standing_Calf_Raises': 'Подъемы на носки стоя',
  'Standing_Concentration_Curl': 'Концентрированные сгибания рук стоя',
  'Standing_Dumbbell_Calf_Raise': 'Подъемы на носки с гантелями стоя',
  'Standing_Dumbbell_Press': 'Жим гантелей стоя',
  'Standing_Dumbbell_Reverse_Curl': 'Обратные сгибания рук с гантелями стоя',
  'Standing_Dumbbell_Straight-Arm_Front_Delt_Raise_Above_Head': 'Подъем прямых рук с гантелями перед собой выше головы',
  'Standing_Dumbbell_Triceps_Extension': 'Разгибание рук на трицепс с гантелью стоя',
  'Standing_Dumbbell_Upright_Row': 'Тяга гантелей к подбородку стоя',
  'Standing_Elevated_Quad_Stretch': 'Растяжка квадрицепса стоя на возвышении',
  'Standing_Front_Barbell_Raise_Over_Head': 'Подъем штанги перед собой над головой',
  'Standing_Gastrocnemius_Calf_Stretch': 'Растяжка икроножной мышцы стоя',
  'Standing_Hamstring_and_Calf_Stretch': 'Растяжка задней поверхности бедра и икроножных стоя',
  'Standing_Hip_Circles': 'Вращения тазом стоя',
  'Standing_Hip_Flexors': 'Разминка сгибателей бедра стоя',
  'Standing_Inner-Biceps_Curl': 'Сгибание рук на внутренний пучок бицепса стоя',
  'Standing_Lateral_Stretch': 'Боковая растяжка стоя',
  'Standing_Leg_Curl': 'Сгибание ног стоя в тренажере',
  'Standing_Long_Jump': 'Прыжок в длину с места',
  'Standing_Low-Pulley_Deltoid_Raise': 'Отведение руки в сторону на нижнем блоке',
  'Standing_Low-Pulley_One-Arm_Triceps_Extension': 'Разгибание одной руки на трицепс на нижнем блоке',
  'Standing_Military_Press': 'Армейский жим стоя',
  'Standing_Olympic_Plate_Hand_Squeeze': 'Удержание дисков пальцами стоя',
  'Standing_One-Arm_Cable_Curl': 'Сгибание одной руки на нижнем блоке стоя',
  'Standing_One-Arm_Dumbbell_Curl_Over_Incline_Bench': 'Сгибание одной руки с гантелью с упором на наклонную скамью',
  'Standing_One-Arm_Dumbbell_Triceps_Extension': 'Разгибание одной руки на трицепс с гантелью стоя',
  'Standing_Overhead_Barbell_Triceps_Extension': 'Французский жим со штангой стоя',
  'Standing_Palm-In_One-Arm_Dumbbell_Press': 'Жим одной гантели стоя ладонью внутрь',
  'Standing_Palms-In_Dumbbell_Press': 'Жим гантелей стоя ладонями внутрь',
  'Standing_Palms-Up_Barbell_Behind_The_Back_Wrist_Curl': 'Сгибание запястий со штангой за спиной стоя',
  'Standing_Pelvic_Tilt': 'Наклон таза стоя',
  'Standing_Rope_Crunch': 'Скручивания на блоке стоя с канатом',
  'Standing_Soleus_And_Achilles_Stretch': 'Растяжка камбаловидной мышцы и ахиллова сухожилия',
  'Standing_Toe_Touches': 'Наклоны вперед до касания пальцев ног',
  'Standing_Towel_Triceps_Extension': 'Разгибание рук на трицепс с полотенцем',
  'Standing_Two-Arm_Overhead_Throw': 'Бросок мяча двумя руками из-за головы',
  'Star_Jump': 'Прыжок «Звезда»',
  'Step-up_with_Knee_Raise': 'Зашагивания на платформу с подъемом колена',
  'Step_Mill': 'Шаговый тренажер',
  'Stiff-Legged_Barbell_Deadlift': 'Становая тяга на прямых ногах со штангой',
  'Stiff-Legged_Dumbbell_Deadlift': 'Становая тяга на прямых ногах с гантелями',
  'Stiff_Leg_Barbell_Good_Morning': 'Наклоны со штангой на прямых ногах',
  'Stomach_Vacuum': 'Вакуум живота',
  'Straight-Arm_Dumbbell_Pullover': 'Пуловер с гантелью на прямых руках',
  'Straight-Arm_Pulldown': 'Пуловер на верхнем блоке на прямых руках',
  'Straight_Bar_Bench_Mid_Rows': 'Тяга прямой рукояти к животу на горизонтальном блоке',
  'Straight_Raises_on_Incline_Bench': 'Подъемы прямых рук на наклонной скамье',
  'Stride_Jump_Crossover': 'Прыжки скрестным широким шагом',
  'Sumo_Deadlift': 'Становая тяга сумо',
  'Sumo_Deadlift_with_Bands': 'Становая тяга сумо с амортизатором',
  'Sumo_Deadlift_with_Chains': 'Становая тяга сумо с цепями',
  'Superman': 'Супермен',
  'Supine_Chest_Throw': 'Бросок мяча от груди лежа на спине',
  'Supine_One-Arm_Overhead_Throw': 'Бросок мяча одной рукой из-за головы лежа',
  'Supine_Two-Arm_Overhead_Throw': 'Бросок мяча двумя руками из-за головы лежа',
  'Suspended_Fallout': 'Наклоны вперед в петлях TRX',
  'Suspended_Push-Up': 'Отжимания в петлях TRX',
  'Suspended_Reverse_Crunch': 'Обратные скручивания в петлях TRX',
  'Suspended_Row': 'Тяга в петлях TRX',
  'Suspended_Split_Squat': 'Болгарские сплит-приседания в петлях TRX',
  'Svend_Press': 'Жим Свенда',
  'T-Bar_Row_with_Handle': 'Тяга Т-грифа с рукоятью',
  'Tate_Press': 'Жим Тейта',
  'The_Straddle': 'Растяжка ноги в стороны',
  'Thigh_Abductor': 'Разведение ног в тренажере',
  'Thigh_Adductor': 'Сведение ног в тренажере',
  'Tire_Flip': 'Кантование покрышки',
  'Toe_Touchers': 'Скручивания с касанием пальцев ног',
  'Torso_Rotation': 'Повороты корпуса',
  'Trail_Running_Walking': 'Бег по пересеченной местности',
  'Trap_Bar_Deadlift': 'Становая тяга с трэп-грифом',
  'Tricep_Dumbbell_Kickback': 'Разгибание рук назад с гантелями',
  'Tricep_Side_Stretch': 'Боковая растяжка трицепса',
  'Triceps_Overhead_Extension_with_Rope': 'Разгибание рук на трицепс из-за головы с канатом',
  'Triceps_Pushdown': 'Разгибание рук на трицепс на верхнем блоке',
  'Triceps_Pushdown_-_Rope_Attachment': 'Разгибание рук на трицепс с канатом',
  'Triceps_Pushdown_-_V-Bar_Attachment': 'Разгибание рук на трицепс с V-рукоятью',
  'Triceps_Stretch': 'Растяжка трицепса',
  'Tuck_Crunch': 'Скручивания со сгибанием коленей',
  'Two-Arm_Dumbbell_Preacher_Curl': 'Сгибание рук с гантелями на скамье Скотта',
  'Two-Arm_Kettlebell_Clean': 'Взятие двух гирь на грудь',
  'Two-Arm_Kettlebell_Jerk': 'Толчок двух гирь',
  'Two-Arm_Kettlebell_Military_Press': 'Армейский жим двух гирь',
  'Two-Arm_Kettlebell_Row': 'Тяга двух гирь в наклоне',
  'Underhand_Cable_Pulldowns': 'Тяга верхнего блока обратным хватом',
  'Upper_Back-Leg_Grab': 'Наклон к ногам с захватом',
  'Upper_Back_Stretch': 'Растяжка верхней части спины',
  'Upright_Barbell_Row': 'Тяга штанги к подбородку',
  'Upright_Cable_Row': 'Тяга к подбородку на блоке',
  'Upright_Row_-_With_Bands': 'Тяга к подбородку с амортизатором',
  'Upward_Stretch': 'Растяжка вверх',
  'V-Bar_Pulldown': 'Тяга верхнего блока V-рукоятью',
  'V-Bar_Pullup': 'Подтягивания на V-рукояти',
  'Vertical_Swing': 'Вертикальные махи гирей',
  'Walking_Treadmill': 'Ходьба на беговой дорожке',
  'Weighted_Ball_Hyperextension': 'Гиперэкстензия с медицинским мячом',
  'Weighted_Ball_Side_Bend': 'Наклоны в стороны с медицинским мячом',
  'Weighted_Bench_Dip': 'Отжимания от скамьи с дополнительным весом',
  'Weighted_Crunches': 'Скручивания с дополнительным весом',
  'Weighted_Jump_Squat': 'Выпрыгивания из приседа с весом',
  'Weighted_Pull_Ups': 'Подтягивания с дополнительным весом',
  'Weighted_Sissy_Squat': 'Сисси-приседания с весом',
  'Weighted_Sit-Ups_-_With_Bands': 'Подъемы корпуса с весом и амортизатором',
  'Weighted_Squat': 'Приседания с дополнительным весом',
  'Wide-Grip_Barbell_Bench_Press': 'Жим штанги лежа широким хватом',
  'Wide-Grip_Decline_Barbell_Bench_Press': 'Жим штанги с наклоном вниз широким хватом',
  'Wide-Grip_Decline_Barbell_Pullover': 'Пуловер со штангой широким хватом с наклоном вниз',
  'Wide-Grip_Lat_Pulldown': 'Тяга верхнего блока широким хватом',
  'Wide-Grip_Pulldown_Behind_The_Neck': 'Тяга верхнего блока за голову широким хватом',
  'Wide-Grip_Rear_Pull-Up': 'Подтягивания за голову широким хватом',
  'Wide-Grip_Standing_Barbell_Curl': 'Сгибание рук со штангой широким хватом стоя',
  'Wide_Stance_Barbell_Squat': 'Приседания со штангой в широкой стойке',
  'Wide_Stance_Stiff_Legs': 'Становая тяга на прямых ногах в широкой стойке',
  'Wind_Sprints': 'Интервальные спринты',
  'Windmills': 'Мельница',
  'Worlds_Greatest_Stretch': 'Лучшая растяжка в мире',
  'Wrist_Circles': 'Вращения кистями',
  'Wrist_Roller': 'Ролик для предплечий',
  'Wrist_Rotations_with_Straight_Bar': 'Вращения запястий с прямым грифом',
  'Yoke_Walk': 'Прогулка с коромыслом',
  'Zercher_Squats': 'Приседания Зерхера',
  'Zottman_Curl': 'Сгибания Зоттмана',
  'Zottman_Preacher_Curl': 'Сгибания Зоттмана на скамье Скотта',
};

const EXERCISES_URL =
  'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/dist/exercises.json';

async function fetchExercises(): Promise<RawExercise[]> {
  const localPath = path.join(process.cwd(), 'prisma', 'exercises.json');
  if (fs.existsSync(localPath)) {
    return JSON.parse(fs.readFileSync(localPath, 'utf-8'));
  }
  console.log('exercises.json not found locally, downloading from source...');
  const res = await fetch(EXERCISES_URL);
  if (!res.ok) throw new Error(`Failed to fetch exercises: ${res.status}`);
  return res.json();
}

async function main() {
  const raw = await fetchExercises();

  console.log(`Seeding ${raw.length} exercises...`);

  await prisma.exercise.deleteMany();

  const data = raw.map((ex) => ({
    id: ex.id,
    name: ex.name,
    nameRu: TRANSLATIONS[ex.id] ?? null,
    category: ex.category,
    primaryMuscles: ex.primaryMuscles,
    secondaryMuscles: ex.secondaryMuscles,
    equipment: ex.equipment ?? null,
    images: ex.images,
  }));

  const result = await prisma.exercise.createMany({ data, skipDuplicates: true });

  console.log(`Done. ${result.count} exercises seeded.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
